// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package update

import (
	"encoding/json"
	"fmt"
	"strings"

	zeus "github.com/getbread/breadkit/zeus/types"
)

type AnalyticsOrderUpdateField int

const (
	AnalyticsOrderUpdate_CustomerEmail AnalyticsOrderUpdateField = iota
	AnalyticsOrderUpdate_TotalPrice
	AnalyticsOrderUpdate_Gateway
	AnalyticsOrderUpdate_FinancialStatus
	AnalyticsOrderUpdate_FulfillmentStatus
	AnalyticsOrderUpdate_Redacted
	AnalyticsOrderUpdate_UpdatedAt
)

func (s AnalyticsOrderUpdateField) MarshalText() ([]byte, error) {

	var data string

	switch s {
	case AnalyticsOrderUpdate_CustomerEmail:
		data = "customerEmail"
	case AnalyticsOrderUpdate_TotalPrice:
		data = "totalPrice"
	case AnalyticsOrderUpdate_Gateway:
		data = "gateway"
	case AnalyticsOrderUpdate_FinancialStatus:
		data = "financialStatus"
	case AnalyticsOrderUpdate_FulfillmentStatus:
		data = "fulfillmentStatus"
	case AnalyticsOrderUpdate_Redacted:
		data = "redacted"
	case AnalyticsOrderUpdate_UpdatedAt:
		data = "updatedAt"

	default:
		return nil, fmt.Errorf("Cannot marshal text '%v'", s)
	}

	return []byte(data), nil

}

func (s *AnalyticsOrderUpdateField) UnmarshalText(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "customerEmail":
		*s = AnalyticsOrderUpdate_CustomerEmail
	case "totalPrice":
		*s = AnalyticsOrderUpdate_TotalPrice
	case "gateway":
		*s = AnalyticsOrderUpdate_Gateway
	case "financialStatus":
		*s = AnalyticsOrderUpdate_FinancialStatus
	case "fulfillmentStatus":
		*s = AnalyticsOrderUpdate_FulfillmentStatus
	case "redacted":
		*s = AnalyticsOrderUpdate_Redacted
	case "updatedAt":
		*s = AnalyticsOrderUpdate_UpdatedAt

	default:
		return fmt.Errorf("Cannot unmarshal text '%s'", str)
	}

	return nil

}

func (s AnalyticsOrderUpdateField) String() string {
	switch s {
	case AnalyticsOrderUpdate_CustomerEmail:
		return "customer_email"
	case AnalyticsOrderUpdate_TotalPrice:
		return "total_price"
	case AnalyticsOrderUpdate_Gateway:
		return "gateway"
	case AnalyticsOrderUpdate_FinancialStatus:
		return "financial_status"
	case AnalyticsOrderUpdate_FulfillmentStatus:
		return "fulfillment_status"
	case AnalyticsOrderUpdate_Redacted:
		return "redacted"
	case AnalyticsOrderUpdate_UpdatedAt:
		return "updated_at"

	}
	return ""
}

type AnalyticsOrderUpdateRequest struct {
	Id      zeus.Uuid                                 `json:"id"`
	Updates map[AnalyticsOrderUpdateField]interface{} `json:"updates"`
}

func (ur AnalyticsOrderUpdateRequest) MarshalText() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur AnalyticsOrderUpdateRequest) MarshalBinary() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur *AnalyticsOrderUpdateRequest) UnmarshalText(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[AnalyticsOrderUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p AnalyticsOrderUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

func (ur *AnalyticsOrderUpdateRequest) UnmarshalBinary(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[AnalyticsOrderUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p AnalyticsOrderUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

// implement updater.UpdateRequest interface
func (ur *AnalyticsOrderUpdateRequest) GetId() zeus.Uuid {
	return ur.Id
}

func (ur *AnalyticsOrderUpdateRequest) GetTableName() string {
	return "shopify_analytics_orders"
}

func (ur *AnalyticsOrderUpdateRequest) GetUpdates() map[string]interface{} {
	updates := make(map[string]interface{})

	for field, value := range ur.Updates {
		updates[field.String()] = value
	}

	return updates
}

func (ur *AnalyticsOrderUpdateRequest) AddUpdate(field AnalyticsOrderUpdateField, value interface{}) {
	if ur.Updates == nil {
		ur.Updates = make(map[AnalyticsOrderUpdateField]interface{})
	}

	ur.Updates[field] = value
}
