// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package update

import (
	"encoding/json"
	"fmt"
	"strings"

	zeus "github.com/getbread/breadkit/zeus/types"
)

type DraftOrderCartUpdateField int

const (
	DraftOrderCartUpdate_DraftOrderID DraftOrderCartUpdateField = iota
	DraftOrderCartUpdate_CartID
	DraftOrderCartUpdate_CartURL
	DraftOrderCartUpdate_IsProduction
	DraftOrderCartUpdate_IsDeleted
	DraftOrderCartUpdate_UseDraftOrderAsOrder
	DraftOrderCartUpdate_UpdatedAt
)

func (s DraftOrderCartUpdateField) MarshalText() ([]byte, error) {

	var data string

	switch s {
	case DraftOrderCartUpdate_DraftOrderID:
		data = "draftOrderId"
	case DraftOrderCartUpdate_CartID:
		data = "cartId"
	case DraftOrderCartUpdate_CartURL:
		data = "cartUrl"
	case DraftOrderCartUpdate_IsProduction:
		data = "isProduction"
	case DraftOrderCartUpdate_IsDeleted:
		data = "isDeleted"
	case DraftOrderCartUpdate_UseDraftOrderAsOrder:
		data = "useDraftOrderAsOrder"
	case DraftOrderCartUpdate_UpdatedAt:
		data = "updatedAt"

	default:
		return nil, fmt.Errorf("Cannot marshal text '%v'", s)
	}

	return []byte(data), nil

}

func (s *DraftOrderCartUpdateField) UnmarshalText(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "draftOrderId":
		*s = DraftOrderCartUpdate_DraftOrderID
	case "cartId":
		*s = DraftOrderCartUpdate_CartID
	case "cartUrl":
		*s = DraftOrderCartUpdate_CartURL
	case "isProduction":
		*s = DraftOrderCartUpdate_IsProduction
	case "isDeleted":
		*s = DraftOrderCartUpdate_IsDeleted
	case "useDraftOrderAsOrder":
		*s = DraftOrderCartUpdate_UseDraftOrderAsOrder
	case "updatedAt":
		*s = DraftOrderCartUpdate_UpdatedAt

	default:
		return fmt.Errorf("Cannot unmarshal text '%s'", str)
	}

	return nil

}

func (s DraftOrderCartUpdateField) String() string {
	switch s {
	case DraftOrderCartUpdate_DraftOrderID:
		return "draft_order_id"
	case DraftOrderCartUpdate_CartID:
		return "cart_id"
	case DraftOrderCartUpdate_CartURL:
		return "cart_url"
	case DraftOrderCartUpdate_IsProduction:
		return "is_production"
	case DraftOrderCartUpdate_IsDeleted:
		return "is_deleted"
	case DraftOrderCartUpdate_UseDraftOrderAsOrder:
		return "use_draft_order_as_order"
	case DraftOrderCartUpdate_UpdatedAt:
		return "updated_at"

	}
	return ""
}

type DraftOrderCartUpdateRequest struct {
	Id      zeus.Uuid                                 `json:"id"`
	Updates map[DraftOrderCartUpdateField]interface{} `json:"updates"`
}

func (ur DraftOrderCartUpdateRequest) MarshalText() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur DraftOrderCartUpdateRequest) MarshalBinary() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur *DraftOrderCartUpdateRequest) UnmarshalText(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[DraftOrderCartUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p DraftOrderCartUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

func (ur *DraftOrderCartUpdateRequest) UnmarshalBinary(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[DraftOrderCartUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p DraftOrderCartUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

// implement updater.UpdateRequest interface
func (ur *DraftOrderCartUpdateRequest) GetId() zeus.Uuid {
	return ur.Id
}

func (ur *DraftOrderCartUpdateRequest) GetTableName() string {
	return "shopify_shops_draft_order_carts"
}

func (ur *DraftOrderCartUpdateRequest) GetUpdates() map[string]interface{} {
	updates := make(map[string]interface{})

	for field, value := range ur.Updates {
		updates[field.String()] = value
	}

	return updates
}

func (ur *DraftOrderCartUpdateRequest) AddUpdate(field DraftOrderCartUpdateField, value interface{}) {
	if ur.Updates == nil {
		ur.Updates = make(map[DraftOrderCartUpdateField]interface{})
	}

	ur.Updates[field] = value
}
