// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package update

import (
	"encoding/json"
	"fmt"
	"strings"

	zeus "github.com/getbread/breadkit/zeus/types"
)

type GatewayPasswordResetRequestUpdateField int

const (
	GatewayPasswordResetRequestUpdate_TokenHash GatewayPasswordResetRequestUpdateField = iota
	GatewayPasswordResetRequestUpdate_Expiration
	GatewayPasswordResetRequestUpdate_UpdatedAt
)

func (s GatewayPasswordResetRequestUpdateField) MarshalText() ([]byte, error) {

	var data string

	switch s {
	case GatewayPasswordResetRequestUpdate_TokenHash:
		data = "_"
	case GatewayPasswordResetRequestUpdate_Expiration:
		data = "expiration"
	case GatewayPasswordResetRequestUpdate_UpdatedAt:
		data = "updatedAt"

	default:
		return nil, fmt.Errorf("Cannot marshal text '%v'", s)
	}

	return []byte(data), nil

}

func (s *GatewayPasswordResetRequestUpdateField) UnmarshalText(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "_":
		*s = GatewayPasswordResetRequestUpdate_TokenHash
	case "expiration":
		*s = GatewayPasswordResetRequestUpdate_Expiration
	case "updatedAt":
		*s = GatewayPasswordResetRequestUpdate_UpdatedAt

	default:
		return fmt.Errorf("Cannot unmarshal text '%s'", str)
	}

	return nil

}

func (s GatewayPasswordResetRequestUpdateField) String() string {
	switch s {
	case GatewayPasswordResetRequestUpdate_TokenHash:
		return "token_hash"
	case GatewayPasswordResetRequestUpdate_Expiration:
		return "expiration"
	case GatewayPasswordResetRequestUpdate_UpdatedAt:
		return "updated_at"

	}
	return ""
}

type GatewayPasswordResetRequestUpdateRequest struct {
	Id      zeus.Uuid                                              `json:"id"`
	Updates map[GatewayPasswordResetRequestUpdateField]interface{} `json:"updates"`
}

func (ur GatewayPasswordResetRequestUpdateRequest) MarshalText() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur GatewayPasswordResetRequestUpdateRequest) MarshalBinary() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur *GatewayPasswordResetRequestUpdateRequest) UnmarshalText(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[GatewayPasswordResetRequestUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p GatewayPasswordResetRequestUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

func (ur *GatewayPasswordResetRequestUpdateRequest) UnmarshalBinary(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[GatewayPasswordResetRequestUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p GatewayPasswordResetRequestUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

// implement updater.UpdateRequest interface
func (ur *GatewayPasswordResetRequestUpdateRequest) GetId() zeus.Uuid {
	return ur.Id
}

func (ur *GatewayPasswordResetRequestUpdateRequest) GetTableName() string {
	return "shopify_gateway_password_reset_requests"
}

func (ur *GatewayPasswordResetRequestUpdateRequest) GetUpdates() map[string]interface{} {
	updates := make(map[string]interface{})

	for field, value := range ur.Updates {
		updates[field.String()] = value
	}

	return updates
}

func (ur *GatewayPasswordResetRequestUpdateRequest) AddUpdate(field GatewayPasswordResetRequestUpdateField, value interface{}) {
	if ur.Updates == nil {
		ur.Updates = make(map[GatewayPasswordResetRequestUpdateField]interface{})
	}

	ur.Updates[field] = value
}
