// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package update

import (
	"encoding/json"
	"fmt"
	"strings"

	zeus "github.com/getbread/breadkit/zeus/types"
)

type GatewayCheckoutUpdateField int

const (
	GatewayCheckoutUpdate_TransactionID GatewayCheckoutUpdateField = iota
	GatewayCheckoutUpdate_Completed
	GatewayCheckoutUpdate_Errored
	GatewayCheckoutUpdate_UpdatedAt
	GatewayCheckoutUpdate_AmountStr
	GatewayCheckoutUpdate_BreadVersion
	GatewayCheckoutUpdate_MerchantId
)

func (s GatewayCheckoutUpdateField) MarshalText() ([]byte, error) {

	var data string

	switch s {
	case GatewayCheckoutUpdate_TransactionID:
		data = "transaction_id"
	case GatewayCheckoutUpdate_Completed:
		data = "completed"
	case GatewayCheckoutUpdate_Errored:
		data = "errored"
	case GatewayCheckoutUpdate_UpdatedAt:
		data = "updated_at"
	case GatewayCheckoutUpdate_AmountStr:
		data = "amount_str"
	case GatewayCheckoutUpdate_BreadVersion:
		data = "bread_version"
	case GatewayCheckoutUpdate_MerchantId:
		data = "merchant_id"

	default:
		return nil, fmt.Errorf("Cannot marshal text '%v'", s)
	}

	return []byte(data), nil

}

func (s *GatewayCheckoutUpdateField) UnmarshalText(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "transaction_id":
		*s = GatewayCheckoutUpdate_TransactionID
	case "completed":
		*s = GatewayCheckoutUpdate_Completed
	case "errored":
		*s = GatewayCheckoutUpdate_Errored
	case "updated_at":
		*s = GatewayCheckoutUpdate_UpdatedAt
	case "amount_str":
		*s = GatewayCheckoutUpdate_AmountStr
	case "bread_version":
		*s = GatewayCheckoutUpdate_BreadVersion
	case "merchant_id":
		*s = GatewayCheckoutUpdate_MerchantId

	default:
		return fmt.Errorf("Cannot unmarshal text '%s'", str)
	}

	return nil

}

func (s GatewayCheckoutUpdateField) String() string {
	switch s {
	case GatewayCheckoutUpdate_TransactionID:
		return "transaction_id"
	case GatewayCheckoutUpdate_Completed:
		return "completed"
	case GatewayCheckoutUpdate_Errored:
		return "errored"
	case GatewayCheckoutUpdate_UpdatedAt:
		return "updated_at"
	case GatewayCheckoutUpdate_AmountStr:
		return "amount_str"
	case GatewayCheckoutUpdate_BreadVersion:
		return "bread_version"
	case GatewayCheckoutUpdate_MerchantId:
		return "merchant_id"

	}
	return ""
}

type GatewayCheckoutUpdateRequest struct {
	Id      zeus.Uuid                                  `json:"id"`
	Updates map[GatewayCheckoutUpdateField]interface{} `json:"updates"`
}

func (ur GatewayCheckoutUpdateRequest) MarshalText() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur GatewayCheckoutUpdateRequest) MarshalBinary() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur *GatewayCheckoutUpdateRequest) UnmarshalText(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[GatewayCheckoutUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p GatewayCheckoutUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

func (ur *GatewayCheckoutUpdateRequest) UnmarshalBinary(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[GatewayCheckoutUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p GatewayCheckoutUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

// implement updater.UpdateRequest interface
func (ur *GatewayCheckoutUpdateRequest) GetId() zeus.Uuid {
	return ur.Id
}

func (ur *GatewayCheckoutUpdateRequest) GetTableName() string {
	return "shopify_gateway_checkouts"
}

func (ur *GatewayCheckoutUpdateRequest) GetUpdates() map[string]interface{} {
	updates := make(map[string]interface{})

	for field, value := range ur.Updates {
		updates[field.String()] = value
	}

	return updates
}

func (ur *GatewayCheckoutUpdateRequest) AddUpdate(field GatewayCheckoutUpdateField, value interface{}) {
	if ur.Updates == nil {
		ur.Updates = make(map[GatewayCheckoutUpdateField]interface{})
	}

	ur.Updates[field] = value
}
