// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package update

import (
	"encoding/json"
	"fmt"
	"strings"

	zeus "github.com/getbread/breadkit/zeus/types"
)

type GatewaySessionUpdateField int

const (
	GatewaySessionUpdate_Expiration GatewaySessionUpdateField = iota
	GatewaySessionUpdate_UpdatedAt
)

func (s GatewaySessionUpdateField) MarshalText() ([]byte, error) {

	var data string

	switch s {
	case GatewaySessionUpdate_Expiration:
		data = "expiration"
	case GatewaySessionUpdate_UpdatedAt:
		data = "updatedAt"

	default:
		return nil, fmt.Errorf("Cannot marshal text '%v'", s)
	}

	return []byte(data), nil

}

func (s *GatewaySessionUpdateField) UnmarshalText(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "expiration":
		*s = GatewaySessionUpdate_Expiration
	case "updatedAt":
		*s = GatewaySessionUpdate_UpdatedAt

	default:
		return fmt.Errorf("Cannot unmarshal text '%s'", str)
	}

	return nil

}

func (s GatewaySessionUpdateField) String() string {
	switch s {
	case GatewaySessionUpdate_Expiration:
		return "expiration"
	case GatewaySessionUpdate_UpdatedAt:
		return "updated_at"

	}
	return ""
}

type GatewaySessionUpdateRequest struct {
	Id      zeus.Uuid                                 `json:"id"`
	Updates map[GatewaySessionUpdateField]interface{} `json:"updates"`
}

func (ur GatewaySessionUpdateRequest) MarshalText() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur GatewaySessionUpdateRequest) MarshalBinary() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur *GatewaySessionUpdateRequest) UnmarshalText(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[GatewaySessionUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p GatewaySessionUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

func (ur *GatewaySessionUpdateRequest) UnmarshalBinary(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[GatewaySessionUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p GatewaySessionUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

// implement updater.UpdateRequest interface
func (ur *GatewaySessionUpdateRequest) GetId() zeus.Uuid {
	return ur.Id
}

func (ur *GatewaySessionUpdateRequest) GetTableName() string {
	return "shopify_gateway_sessions"
}

func (ur *GatewaySessionUpdateRequest) GetUpdates() map[string]interface{} {
	updates := make(map[string]interface{})

	for field, value := range ur.Updates {
		updates[field.String()] = value
	}

	return updates
}

func (ur *GatewaySessionUpdateRequest) AddUpdate(field GatewaySessionUpdateField, value interface{}) {
	if ur.Updates == nil {
		ur.Updates = make(map[GatewaySessionUpdateField]interface{})
	}

	ur.Updates[field] = value
}
