// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package update

import (
	"encoding/json"
	"fmt"
	"strings"

	zeus "github.com/getbread/breadkit/zeus/types"
)

type NonceUpdateField int

const (
	NonceUpdate_Nonce NonceUpdateField = iota
	NonceUpdate_UpdatedAt
)

func (s NonceUpdateField) MarshalText() ([]byte, error) {

	var data string

	switch s {
	case NonceUpdate_Nonce:
		data = "nonce"
	case NonceUpdate_UpdatedAt:
		data = "updated_at"

	default:
		return nil, fmt.Errorf("Cannot marshal text '%v'", s)
	}

	return []byte(data), nil

}

func (s *NonceUpdateField) UnmarshalText(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "nonce":
		*s = NonceUpdate_Nonce
	case "updated_at":
		*s = NonceUpdate_UpdatedAt

	default:
		return fmt.Errorf("Cannot unmarshal text '%s'", str)
	}

	return nil

}

func (s NonceUpdateField) String() string {
	switch s {
	case NonceUpdate_Nonce:
		return "nonce"
	case NonceUpdate_UpdatedAt:
		return "updated_at"

	}
	return ""
}

type NonceUpdateRequest struct {
	Id      zeus.Uuid                        `json:"id"`
	Updates map[NonceUpdateField]interface{} `json:"updates"`
}

func (ur NonceUpdateRequest) MarshalText() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur NonceUpdateRequest) MarshalBinary() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur *NonceUpdateRequest) UnmarshalText(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[NonceUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p NonceUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

func (ur *NonceUpdateRequest) UnmarshalBinary(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[NonceUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p NonceUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

// implement updater.UpdateRequest interface
func (ur *NonceUpdateRequest) GetId() zeus.Uuid {
	return ur.Id
}

func (ur *NonceUpdateRequest) GetTableName() string {
	return "shopify_shops_nonces"
}

func (ur *NonceUpdateRequest) GetUpdates() map[string]interface{} {
	updates := make(map[string]interface{})

	for field, value := range ur.Updates {
		updates[field.String()] = value
	}

	return updates
}

func (ur *NonceUpdateRequest) AddUpdate(field NonceUpdateField, value interface{}) {
	if ur.Updates == nil {
		ur.Updates = make(map[NonceUpdateField]interface{})
	}

	ur.Updates[field] = value
}
