// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package update

import (
	"encoding/json"
	"fmt"
	"strings"

	zeus "github.com/getbread/breadkit/zeus/types"
)

type PlusGatewayCheckoutUpdateField int

const (
	PlusGatewayCheckoutUpdate_UpdatedAt PlusGatewayCheckoutUpdateField = iota
)

func (s PlusGatewayCheckoutUpdateField) MarshalText() ([]byte, error) {

	var data string

	switch s {
	case PlusGatewayCheckoutUpdate_UpdatedAt:
		data = "updated_at"

	default:
		return nil, fmt.Errorf("Cannot marshal text '%v'", s)
	}

	return []byte(data), nil

}

func (s *PlusGatewayCheckoutUpdateField) UnmarshalText(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "updated_at":
		*s = PlusGatewayCheckoutUpdate_UpdatedAt

	default:
		return fmt.Errorf("Cannot unmarshal text '%s'", str)
	}

	return nil

}

func (s PlusGatewayCheckoutUpdateField) String() string {
	switch s {
	case PlusGatewayCheckoutUpdate_UpdatedAt:
		return "updated_at"

	}
	return ""
}

type PlusGatewayCheckoutUpdateRequest struct {
	Id      zeus.Uuid                                      `json:"id"`
	Updates map[PlusGatewayCheckoutUpdateField]interface{} `json:"updates"`
}

func (ur PlusGatewayCheckoutUpdateRequest) MarshalText() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur PlusGatewayCheckoutUpdateRequest) MarshalBinary() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur *PlusGatewayCheckoutUpdateRequest) UnmarshalText(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[PlusGatewayCheckoutUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p PlusGatewayCheckoutUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

func (ur *PlusGatewayCheckoutUpdateRequest) UnmarshalBinary(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[PlusGatewayCheckoutUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p PlusGatewayCheckoutUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

// implement updater.UpdateRequest interface
func (ur *PlusGatewayCheckoutUpdateRequest) GetId() zeus.Uuid {
	return ur.Id
}

func (ur *PlusGatewayCheckoutUpdateRequest) GetTableName() string {
	return "shopify_plus_gateway_checkouts"
}

func (ur *PlusGatewayCheckoutUpdateRequest) GetUpdates() map[string]interface{} {
	updates := make(map[string]interface{})

	for field, value := range ur.Updates {
		updates[field.String()] = value
	}

	return updates
}

func (ur *PlusGatewayCheckoutUpdateRequest) AddUpdate(field PlusGatewayCheckoutUpdateField, value interface{}) {
	if ur.Updates == nil {
		ur.Updates = make(map[PlusGatewayCheckoutUpdateField]interface{})
	}

	ur.Updates[field] = value
}
