// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package update

import (
	"encoding/json"
	"fmt"
	"strings"

	zeus "github.com/getbread/breadkit/zeus/types"
)

type SessionUpdateField int

const (
	SessionUpdate_UpdatedAt SessionUpdateField = iota
)

func (s SessionUpdateField) MarshalText() ([]byte, error) {

	var data string

	switch s {
	case SessionUpdate_UpdatedAt:
		data = "updatedAt"

	default:
		return nil, fmt.Errorf("Cannot marshal text '%v'", s)
	}

	return []byte(data), nil

}

func (s *SessionUpdateField) UnmarshalText(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "updatedAt":
		*s = SessionUpdate_UpdatedAt

	default:
		return fmt.Errorf("Cannot unmarshal text '%s'", str)
	}

	return nil

}

func (s SessionUpdateField) String() string {
	switch s {
	case SessionUpdate_UpdatedAt:
		return "updated_at"

	}
	return ""
}

type SessionUpdateRequest struct {
	Id      zeus.Uuid                          `json:"id"`
	Updates map[SessionUpdateField]interface{} `json:"updates"`
}

func (ur SessionUpdateRequest) MarshalText() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur SessionUpdateRequest) MarshalBinary() ([]byte, error) {
	stringified := make(map[string]interface{})

	for key, value := range ur.Updates {
		s, err := key.MarshalText()

		if err != nil {
			return nil, err
		}

		stringified[string(s)] = value
	}

	result := map[string]interface{}{
		"updates": stringified,
		"id":      ur.Id,
	}

	return json.Marshal(result)
}

func (ur *SessionUpdateRequest) UnmarshalText(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[SessionUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p SessionUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

func (ur *SessionUpdateRequest) UnmarshalBinary(b []byte) error {
	var i map[string]interface{}

	err := json.Unmarshal(b, &i)

	if err != nil {
		return err
	}

	ur.Id = zeus.Uuid(i["id"].(string))

	var j = make(map[SessionUpdateField]interface{})

	for key, value := range i["updates"].(map[string]interface{}) {
		var p SessionUpdateField
		err = p.UnmarshalText([]byte(key))

		if err != nil {
			return err
		}
		j[p] = value
	}

	ur.Updates = j

	return nil
}

// implement updater.UpdateRequest interface
func (ur *SessionUpdateRequest) GetId() zeus.Uuid {
	return ur.Id
}

func (ur *SessionUpdateRequest) GetTableName() string {
	return "shopify_shops_sessions"
}

func (ur *SessionUpdateRequest) GetUpdates() map[string]interface{} {
	updates := make(map[string]interface{})

	for field, value := range ur.Updates {
		updates[field.String()] = value
	}

	return updates
}

func (ur *SessionUpdateRequest) AddUpdate(field SessionUpdateField, value interface{}) {
	if ur.Updates == nil {
		ur.Updates = make(map[SessionUpdateField]interface{})
	}

	ur.Updates[field] = value
}
