version: "3.7"

services:
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_PASSWORD=mooncakes
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  redis:
    image: redis:6.0.8-alpine
    ports:
      - "6381:6379"
    volumes:
      - redisdata:/data
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
