apiVersion: v1
kind: Secret
metadata:
  name: shopify-plugin-backend-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    {{- include "service.config" . | fromYaml | toYaml | b64enc | nindent 4 }}
