// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/searcher. DO NOT EDIT.

package search

import (
	"fmt"
	"strings"

	"github.com/getbread/breadkit/zeus/searcher"

	zeus "github.com/getbread/breadkit/zeus/types"
)

type DraftOrderCartCheckoutSearchField int

const (
	DraftOrderCartCheckoutSearch_ID DraftOrderCartCheckoutSearchField = iota
	DraftOrderCartCheckoutSearch_ShopID
	DraftOrderCartCheckoutSearch_TxID
	DraftOrderCartCheckoutSearch_DraftOrderCartID
	DraftOrderCartCheckoutSearch_OrderID
	DraftOrderCartCheckoutSearch_IsProduction
	DraftOrderCartCheckoutSearch_Completed
	DraftOrderCartCheckoutSearch_Errored
	DraftOrderCartCheckoutSearch_CreatedAt
	DraftOrderCartCheckoutSearch_UpdatedTime
)

func (s DraftOrderCartCheckoutSearchField) MarshalText() ([]byte, error) {
	var data string

	switch s {
	case DraftOrderCartCheckoutSearch_ID:
		data = "id"
	case DraftOrderCartCheckoutSearch_ShopID:
		data = "shopId"
	case DraftOrderCartCheckoutSearch_TxID:
		data = "txId"
	case DraftOrderCartCheckoutSearch_DraftOrderCartID:
		data = "draftOrderCartId"
	case DraftOrderCartCheckoutSearch_OrderID:
		data = "orderId"
	case DraftOrderCartCheckoutSearch_IsProduction:
		data = "isProduction"
	case DraftOrderCartCheckoutSearch_Completed:
		data = "completed"
	case DraftOrderCartCheckoutSearch_Errored:
		data = "errored"
	case DraftOrderCartCheckoutSearch_CreatedAt:
		data = "createdAt"
	case DraftOrderCartCheckoutSearch_UpdatedTime:
		data = "updatedAt"

	default:
		return nil, fmt.Errorf("Cannot marshal text '%v'", s)
	}
	return []byte(data), nil
}

func (s DraftOrderCartCheckoutSearchField) MarshalBinary() ([]byte, error) {
	var data string

	switch s {
	case DraftOrderCartCheckoutSearch_ID:
		data = "id"
	case DraftOrderCartCheckoutSearch_ShopID:
		data = "shopId"
	case DraftOrderCartCheckoutSearch_TxID:
		data = "txId"
	case DraftOrderCartCheckoutSearch_DraftOrderCartID:
		data = "draftOrderCartId"
	case DraftOrderCartCheckoutSearch_OrderID:
		data = "orderId"
	case DraftOrderCartCheckoutSearch_IsProduction:
		data = "isProduction"
	case DraftOrderCartCheckoutSearch_Completed:
		data = "completed"
	case DraftOrderCartCheckoutSearch_Errored:
		data = "errored"
	case DraftOrderCartCheckoutSearch_CreatedAt:
		data = "createdAt"
	case DraftOrderCartCheckoutSearch_UpdatedTime:
		data = "updatedAt"

	default:
		return nil, fmt.Errorf("Cannot marshal binary '%v'", s)
	}
	return []byte(data), nil
}

func (s *DraftOrderCartCheckoutSearchField) UnmarshalText(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "id":
		*s = DraftOrderCartCheckoutSearch_ID
	case "shopId":
		*s = DraftOrderCartCheckoutSearch_ShopID
	case "txId":
		*s = DraftOrderCartCheckoutSearch_TxID
	case "draftOrderCartId":
		*s = DraftOrderCartCheckoutSearch_DraftOrderCartID
	case "orderId":
		*s = DraftOrderCartCheckoutSearch_OrderID
	case "isProduction":
		*s = DraftOrderCartCheckoutSearch_IsProduction
	case "completed":
		*s = DraftOrderCartCheckoutSearch_Completed
	case "errored":
		*s = DraftOrderCartCheckoutSearch_Errored
	case "createdAt":
		*s = DraftOrderCartCheckoutSearch_CreatedAt
	case "updatedAt":
		*s = DraftOrderCartCheckoutSearch_UpdatedTime

	default:
		return fmt.Errorf("Cannot unmarshal text '%s'", str)
	}
	return nil
}

func (s *DraftOrderCartCheckoutSearchField) UnmarshalBinary(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "id":
		*s = DraftOrderCartCheckoutSearch_ID
	case "shopId":
		*s = DraftOrderCartCheckoutSearch_ShopID
	case "txId":
		*s = DraftOrderCartCheckoutSearch_TxID
	case "draftOrderCartId":
		*s = DraftOrderCartCheckoutSearch_DraftOrderCartID
	case "orderId":
		*s = DraftOrderCartCheckoutSearch_OrderID
	case "isProduction":
		*s = DraftOrderCartCheckoutSearch_IsProduction
	case "completed":
		*s = DraftOrderCartCheckoutSearch_Completed
	case "errored":
		*s = DraftOrderCartCheckoutSearch_Errored
	case "createdAt":
		*s = DraftOrderCartCheckoutSearch_CreatedAt
	case "updatedAt":
		*s = DraftOrderCartCheckoutSearch_UpdatedTime

	default:
		return fmt.Errorf("Cannot unmarshal binary '%s'", str)
	}
	return nil
}

func (s DraftOrderCartCheckoutSearchField) DbFieldName() string {
	switch s {
	case DraftOrderCartCheckoutSearch_ID:
		return "id"
	case DraftOrderCartCheckoutSearch_ShopID:
		return "shop_id"
	case DraftOrderCartCheckoutSearch_TxID:
		return "tx_id"
	case DraftOrderCartCheckoutSearch_DraftOrderCartID:
		return "draft_order_cart_id"
	case DraftOrderCartCheckoutSearch_OrderID:
		return "order_id"
	case DraftOrderCartCheckoutSearch_IsProduction:
		return "is_production"
	case DraftOrderCartCheckoutSearch_Completed:
		return "completed"
	case DraftOrderCartCheckoutSearch_Errored:
		return "errored"
	case DraftOrderCartCheckoutSearch_CreatedAt:
		return "created_at"
	case DraftOrderCartCheckoutSearch_UpdatedTime:
		return "updated_at"

	}
	return ""
}

type DraftOrderCartCheckoutSearchRequest struct {
	searcher.SearchRequestFields

	Filters     []DraftOrderCartCheckoutSearchFilter `json:"filters"`
	FilterGroup searcher.FilterGroup                 `json:"filterGroup"`
	OrderBy     DraftOrderCartCheckoutOrderBy        `json:"orderBy"`
	OrderBys    []DraftOrderCartCheckoutOrderBy      `json:"orderBys"`
	Fields      []DraftOrderCartCheckoutSearchField  `json:"fields"`
	IsByID      bool                                 `json:"isById"`
}

type DraftOrderCartCheckoutSearchFilter struct {
	Field     DraftOrderCartCheckoutSearchField `json:"field"`
	Value     interface{}                       `json:"value"`
	Operator  searcher.FilterOperator           `json:"operator"`
	Condition searcher.FilterCondition          `json:"condition"`
}

type DraftOrderCartCheckoutOrderBy struct {
	Field      DraftOrderCartCheckoutSearchField `json:"field"`
	Descending bool                              `json:"desc"`
}

/*
DraftOrderCartCheckoutByID constructs a DraftOrderCartCheckoutSearchRequest to pull
a DraftOrderCartCheckout by it's ID.

You can add additional options using functions.

Handlers may choose to return (*DraftOrderCartCheckout, error) by checking the
IsSearchByID() function.
*/
func DraftOrderCartCheckoutByID(ID zeus.Uuid, options ...func(*DraftOrderCartCheckoutSearchRequest)) DraftOrderCartCheckoutSearchRequest {
	var searchRequest DraftOrderCartCheckoutSearchRequest

	searchRequest.AddFilter(
		DraftOrderCartCheckoutSearch_ID,
		ID,
		searcher.Operator_EQ,
		searcher.Condition_AND)

	searchRequest.Limit = 1
	searchRequest.IsByID = true

	for _, f := range options {
		f(&searchRequest)
	}

	return searchRequest
}

// implement searcher.SearchRequest interface
func (sr *DraftOrderCartCheckoutSearchRequest) GetTableName() string {
	return "shopify_shops_draft_order_cart_checkouts"
}

func (sr *DraftOrderCartCheckoutSearchRequest) GetFilters() []searcher.Filter {
	filters := []searcher.Filter{}

	for _, f := range sr.Filters {
		filter := searcher.Filter{
			Field:     f.Field,
			Value:     f.Value,
			Operator:  f.Operator,
			Condition: f.Condition,
		}
		filters = append(filters, filter)
	}

	return filters
}

func (sr *DraftOrderCartCheckoutSearchRequest) GetFilterGroup() searcher.FilterGroup {
	return sr.FilterGroup
}

func (sr *DraftOrderCartCheckoutSearchRequest) GetOrderBy() searcher.OrderBy {
	return searcher.OrderBy{
		Field:      sr.OrderBy.Field,
		Descending: sr.OrderBy.Descending,
	}
}

func (sr *DraftOrderCartCheckoutSearchRequest) GetOrderBys() []searcher.OrderBy {
	orderBys := make([]searcher.OrderBy, len(sr.OrderBys))
	for i, value := range sr.OrderBys {
		orderBys[i] = searcher.OrderBy{
			Field:      value.Field,
			Descending: value.Descending,
		}
	}
	return orderBys
}

func (sr *DraftOrderCartCheckoutSearchRequest) GetLimit() int {
	return sr.Limit
}

func (sr *DraftOrderCartCheckoutSearchRequest) GetOffset() int {
	return sr.Offset
}

func (sr *DraftOrderCartCheckoutSearchRequest) IsSearchByID() bool {
	return sr.IsByID
}

func (sr *DraftOrderCartCheckoutSearchRequest) AddFilter(field DraftOrderCartCheckoutSearchField, value interface{}, operator searcher.FilterOperator, condition searcher.FilterCondition) {
	if len(sr.FilterGroup.Filters) > 0 || len(sr.FilterGroup.FilterGroups) > 0 {
		panic("Filters cannot be used with FilterGroups")
	}
	f := DraftOrderCartCheckoutSearchFilter{
		Field:     field,
		Value:     value,
		Operator:  operator,
		Condition: condition,
	}
	sr.Filters = append(sr.Filters, f)
}

func (sr *DraftOrderCartCheckoutSearchRequest) SetFilterGroup(fg searcher.FilterGroup) {
	if len(sr.Filters) > 0 {
		panic("FilterGroups cannot be used with Filters")
	}
	sr.FilterGroup = fg
}

func (sr *DraftOrderCartCheckoutSearchRequest) SetOrderBy(field DraftOrderCartCheckoutSearchField, isDescending bool) {
	sr.OrderBy = DraftOrderCartCheckoutOrderBy{
		Field:      field,
		Descending: isDescending,
	}

	// Set this primary order by as the first in the slice
	sr.OrderBys = []DraftOrderCartCheckoutOrderBy{sr.OrderBy}
}

func (sr *DraftOrderCartCheckoutSearchRequest) SetOrderBys(orderBys ...DraftOrderCartCheckoutOrderBy) {
	sr.OrderBys = append([]DraftOrderCartCheckoutOrderBy{}, orderBys...)
}

func (sr *DraftOrderCartCheckoutSearchRequest) GetAllFields() []string {
	return []string{
		"id",
		"shop_id",
		"tx_id",
		"draft_order_cart_id",
		"order_id",
		"is_production",
		"completed",
		"errored",
		"created_at",
		"updated_at",
	}
}

func (sr *DraftOrderCartCheckoutSearchRequest) GetFields() []string {
	fields := []string{}

	for _, f := range sr.Fields {
		fields = append(fields, f.DbFieldName())
	}

	return fields
}
