// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/searcher. DO NOT EDIT.

package search

import (
	"fmt"
	"strings"

	"github.com/getbread/breadkit/zeus/searcher"

	zeus "github.com/getbread/breadkit/zeus/types"
)

type GatewayPasswordResetRequestSearchField int

const (
	GatewayPasswordResetRequestSearch_ID GatewayPasswordResetRequestSearchField = iota
	GatewayPasswordResetRequestSearch_AccountID
	GatewayPasswordResetRequestSearch_TokenHash
	GatewayPasswordResetRequestSearch_Expiration
	GatewayPasswordResetRequestSearch_CreatedAt
	GatewayPasswordResetRequestSearch_UpdatedAt
)

func (s GatewayPasswordResetRequestSearchField) MarshalText() ([]byte, error) {
	var data string

	switch s {
	case GatewayPasswordResetRequestSearch_ID:
		data = "id"
	case GatewayPasswordResetRequestSearch_AccountID:
		data = "accountId"
	case GatewayPasswordResetRequestSearch_TokenHash:
		data = "_"
	case GatewayPasswordResetRequestSearch_Expiration:
		data = "expiration"
	case GatewayPasswordResetRequestSearch_CreatedAt:
		data = "createdAt"
	case GatewayPasswordResetRequestSearch_UpdatedAt:
		data = "updatedAt"

	default:
		return nil, fmt.Errorf("Cannot marshal text '%v'", s)
	}
	return []byte(data), nil
}

func (s GatewayPasswordResetRequestSearchField) MarshalBinary() ([]byte, error) {
	var data string

	switch s {
	case GatewayPasswordResetRequestSearch_ID:
		data = "id"
	case GatewayPasswordResetRequestSearch_AccountID:
		data = "accountId"
	case GatewayPasswordResetRequestSearch_TokenHash:
		data = "_"
	case GatewayPasswordResetRequestSearch_Expiration:
		data = "expiration"
	case GatewayPasswordResetRequestSearch_CreatedAt:
		data = "createdAt"
	case GatewayPasswordResetRequestSearch_UpdatedAt:
		data = "updatedAt"

	default:
		return nil, fmt.Errorf("Cannot marshal binary '%v'", s)
	}
	return []byte(data), nil
}

func (s *GatewayPasswordResetRequestSearchField) UnmarshalText(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "id":
		*s = GatewayPasswordResetRequestSearch_ID
	case "accountId":
		*s = GatewayPasswordResetRequestSearch_AccountID
	case "_":
		*s = GatewayPasswordResetRequestSearch_TokenHash
	case "expiration":
		*s = GatewayPasswordResetRequestSearch_Expiration
	case "createdAt":
		*s = GatewayPasswordResetRequestSearch_CreatedAt
	case "updatedAt":
		*s = GatewayPasswordResetRequestSearch_UpdatedAt

	default:
		return fmt.Errorf("Cannot unmarshal text '%s'", str)
	}
	return nil
}

func (s *GatewayPasswordResetRequestSearchField) UnmarshalBinary(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "id":
		*s = GatewayPasswordResetRequestSearch_ID
	case "accountId":
		*s = GatewayPasswordResetRequestSearch_AccountID
	case "_":
		*s = GatewayPasswordResetRequestSearch_TokenHash
	case "expiration":
		*s = GatewayPasswordResetRequestSearch_Expiration
	case "createdAt":
		*s = GatewayPasswordResetRequestSearch_CreatedAt
	case "updatedAt":
		*s = GatewayPasswordResetRequestSearch_UpdatedAt

	default:
		return fmt.Errorf("Cannot unmarshal binary '%s'", str)
	}
	return nil
}

func (s GatewayPasswordResetRequestSearchField) DbFieldName() string {
	switch s {
	case GatewayPasswordResetRequestSearch_ID:
		return "id"
	case GatewayPasswordResetRequestSearch_AccountID:
		return "account_id"
	case GatewayPasswordResetRequestSearch_TokenHash:
		return "token_hash"
	case GatewayPasswordResetRequestSearch_Expiration:
		return "expiration"
	case GatewayPasswordResetRequestSearch_CreatedAt:
		return "created_at"
	case GatewayPasswordResetRequestSearch_UpdatedAt:
		return "updated_at"

	}
	return ""
}

type GatewayPasswordResetRequestSearchRequest struct {
	searcher.SearchRequestFields

	Filters     []GatewayPasswordResetRequestSearchFilter `json:"filters"`
	FilterGroup searcher.FilterGroup                      `json:"filterGroup"`
	OrderBy     GatewayPasswordResetRequestOrderBy        `json:"orderBy"`
	OrderBys    []GatewayPasswordResetRequestOrderBy      `json:"orderBys"`
	Fields      []GatewayPasswordResetRequestSearchField  `json:"fields"`
	IsByID      bool                                      `json:"isById"`
}

type GatewayPasswordResetRequestSearchFilter struct {
	Field     GatewayPasswordResetRequestSearchField `json:"field"`
	Value     interface{}                            `json:"value"`
	Operator  searcher.FilterOperator                `json:"operator"`
	Condition searcher.FilterCondition               `json:"condition"`
}

type GatewayPasswordResetRequestOrderBy struct {
	Field      GatewayPasswordResetRequestSearchField `json:"field"`
	Descending bool                                   `json:"desc"`
}

/*
GatewayPasswordResetRequestByID constructs a GatewayPasswordResetRequestSearchRequest to pull
a GatewayPasswordResetRequest by it's ID.

You can add additional options using functions.

Handlers may choose to return (*GatewayPasswordResetRequest, error) by checking the
IsSearchByID() function.
*/
func GatewayPasswordResetRequestByID(ID zeus.Uuid, options ...func(*GatewayPasswordResetRequestSearchRequest)) GatewayPasswordResetRequestSearchRequest {
	var searchRequest GatewayPasswordResetRequestSearchRequest

	searchRequest.AddFilter(
		GatewayPasswordResetRequestSearch_ID,
		ID,
		searcher.Operator_EQ,
		searcher.Condition_AND)

	searchRequest.Limit = 1
	searchRequest.IsByID = true

	for _, f := range options {
		f(&searchRequest)
	}

	return searchRequest
}

// implement searcher.SearchRequest interface
func (sr *GatewayPasswordResetRequestSearchRequest) GetTableName() string {
	return "shopify_gateway_password_reset_requests"
}

func (sr *GatewayPasswordResetRequestSearchRequest) GetFilters() []searcher.Filter {
	filters := []searcher.Filter{}

	for _, f := range sr.Filters {
		filter := searcher.Filter{
			Field:     f.Field,
			Value:     f.Value,
			Operator:  f.Operator,
			Condition: f.Condition,
		}
		filters = append(filters, filter)
	}

	return filters
}

func (sr *GatewayPasswordResetRequestSearchRequest) GetFilterGroup() searcher.FilterGroup {
	return sr.FilterGroup
}

func (sr *GatewayPasswordResetRequestSearchRequest) GetOrderBy() searcher.OrderBy {
	return searcher.OrderBy{
		Field:      sr.OrderBy.Field,
		Descending: sr.OrderBy.Descending,
	}
}

func (sr *GatewayPasswordResetRequestSearchRequest) GetOrderBys() []searcher.OrderBy {
	orderBys := make([]searcher.OrderBy, len(sr.OrderBys))
	for i, value := range sr.OrderBys {
		orderBys[i] = searcher.OrderBy{
			Field:      value.Field,
			Descending: value.Descending,
		}
	}
	return orderBys
}

func (sr *GatewayPasswordResetRequestSearchRequest) GetLimit() int {
	return sr.Limit
}

func (sr *GatewayPasswordResetRequestSearchRequest) GetOffset() int {
	return sr.Offset
}

func (sr *GatewayPasswordResetRequestSearchRequest) IsSearchByID() bool {
	return sr.IsByID
}

func (sr *GatewayPasswordResetRequestSearchRequest) AddFilter(field GatewayPasswordResetRequestSearchField, value interface{}, operator searcher.FilterOperator, condition searcher.FilterCondition) {
	if len(sr.FilterGroup.Filters) > 0 || len(sr.FilterGroup.FilterGroups) > 0 {
		panic("Filters cannot be used with FilterGroups")
	}
	f := GatewayPasswordResetRequestSearchFilter{
		Field:     field,
		Value:     value,
		Operator:  operator,
		Condition: condition,
	}
	sr.Filters = append(sr.Filters, f)
}

func (sr *GatewayPasswordResetRequestSearchRequest) SetFilterGroup(fg searcher.FilterGroup) {
	if len(sr.Filters) > 0 {
		panic("FilterGroups cannot be used with Filters")
	}
	sr.FilterGroup = fg
}

func (sr *GatewayPasswordResetRequestSearchRequest) SetOrderBy(field GatewayPasswordResetRequestSearchField, isDescending bool) {
	sr.OrderBy = GatewayPasswordResetRequestOrderBy{
		Field:      field,
		Descending: isDescending,
	}

	// Set this primary order by as the first in the slice
	sr.OrderBys = []GatewayPasswordResetRequestOrderBy{sr.OrderBy}
}

func (sr *GatewayPasswordResetRequestSearchRequest) SetOrderBys(orderBys ...GatewayPasswordResetRequestOrderBy) {
	sr.OrderBys = append([]GatewayPasswordResetRequestOrderBy{}, orderBys...)
}

func (sr *GatewayPasswordResetRequestSearchRequest) GetAllFields() []string {
	return []string{
		"id",
		"account_id",
		"token_hash",
		"expiration",
		"created_at",
		"updated_at",
	}
}

func (sr *GatewayPasswordResetRequestSearchRequest) GetFields() []string {
	fields := []string{}

	for _, f := range sr.Fields {
		fields = append(fields, f.DbFieldName())
	}

	return fields
}
