// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/searcher. DO NOT EDIT.

package search

import (
	"fmt"
	"strings"

	"github.com/getbread/breadkit/zeus/searcher"

	zeus "github.com/getbread/breadkit/zeus/types"
)

type NonceSearchField int

const (
	NonceSearch_Id NonceSearchField = iota
	NonceSearch_ShopId
	NonceSearch_Nonce
	NonceSearch_CreatedAt
	NonceSearch_UpdatedAt
)

func (s NonceSearchField) MarshalText() ([]byte, error) {
	var data string

	switch s {
	case NonceSearch_Id:
		data = "id"
	case NonceSearch_ShopId:
		data = "shop_id"
	case NonceSearch_Nonce:
		data = "nonce"
	case NonceSearch_CreatedAt:
		data = "created_at"
	case NonceSearch_UpdatedAt:
		data = "updated_at"

	default:
		return nil, fmt.Errorf("Cannot marshal text '%v'", s)
	}
	return []byte(data), nil
}

func (s NonceSearchField) MarshalBinary() ([]byte, error) {
	var data string

	switch s {
	case NonceSearch_Id:
		data = "id"
	case NonceSearch_ShopId:
		data = "shop_id"
	case NonceSearch_Nonce:
		data = "nonce"
	case NonceSearch_CreatedAt:
		data = "created_at"
	case NonceSearch_UpdatedAt:
		data = "updated_at"

	default:
		return nil, fmt.Errorf("Cannot marshal binary '%v'", s)
	}
	return []byte(data), nil
}

func (s *NonceSearchField) UnmarshalText(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "id":
		*s = NonceSearch_Id
	case "shop_id":
		*s = NonceSearch_ShopId
	case "nonce":
		*s = NonceSearch_Nonce
	case "created_at":
		*s = NonceSearch_CreatedAt
	case "updated_at":
		*s = NonceSearch_UpdatedAt

	default:
		return fmt.Errorf("Cannot unmarshal text '%s'", str)
	}
	return nil
}

func (s *NonceSearchField) UnmarshalBinary(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "id":
		*s = NonceSearch_Id
	case "shop_id":
		*s = NonceSearch_ShopId
	case "nonce":
		*s = NonceSearch_Nonce
	case "created_at":
		*s = NonceSearch_CreatedAt
	case "updated_at":
		*s = NonceSearch_UpdatedAt

	default:
		return fmt.Errorf("Cannot unmarshal binary '%s'", str)
	}
	return nil
}

func (s NonceSearchField) DbFieldName() string {
	switch s {
	case NonceSearch_Id:
		return "id"
	case NonceSearch_ShopId:
		return "shop_id"
	case NonceSearch_Nonce:
		return "nonce"
	case NonceSearch_CreatedAt:
		return "created_at"
	case NonceSearch_UpdatedAt:
		return "updated_at"

	}
	return ""
}

type NonceSearchRequest struct {
	searcher.SearchRequestFields

	Filters     []NonceSearchFilter  `json:"filters"`
	FilterGroup searcher.FilterGroup `json:"filterGroup"`
	OrderBy     NonceOrderBy         `json:"orderBy"`
	OrderBys    []NonceOrderBy       `json:"orderBys"`
	Fields      []NonceSearchField   `json:"fields"`
	IsByID      bool                 `json:"isById"`
}

type NonceSearchFilter struct {
	Field     NonceSearchField         `json:"field"`
	Value     interface{}              `json:"value"`
	Operator  searcher.FilterOperator  `json:"operator"`
	Condition searcher.FilterCondition `json:"condition"`
}

type NonceOrderBy struct {
	Field      NonceSearchField `json:"field"`
	Descending bool             `json:"desc"`
}

/*
NonceByID constructs a NonceSearchRequest to pull
a Nonce by it's ID.

You can add additional options using functions.

Handlers may choose to return (*Nonce, error) by checking the
IsSearchByID() function.
*/
func NonceByID(ID zeus.Uuid, options ...func(*NonceSearchRequest)) NonceSearchRequest {
	var searchRequest NonceSearchRequest

	searchRequest.AddFilter(
		NonceSearch_Id,
		ID,
		searcher.Operator_EQ,
		searcher.Condition_AND)

	searchRequest.Limit = 1
	searchRequest.IsByID = true

	for _, f := range options {
		f(&searchRequest)
	}

	return searchRequest
}

// implement searcher.SearchRequest interface
func (sr *NonceSearchRequest) GetTableName() string {
	return "shopify_shops_nonces"
}

func (sr *NonceSearchRequest) GetFilters() []searcher.Filter {
	filters := []searcher.Filter{}

	for _, f := range sr.Filters {
		filter := searcher.Filter{
			Field:     f.Field,
			Value:     f.Value,
			Operator:  f.Operator,
			Condition: f.Condition,
		}
		filters = append(filters, filter)
	}

	return filters
}

func (sr *NonceSearchRequest) GetFilterGroup() searcher.FilterGroup {
	return sr.FilterGroup
}

func (sr *NonceSearchRequest) GetOrderBy() searcher.OrderBy {
	return searcher.OrderBy{
		Field:      sr.OrderBy.Field,
		Descending: sr.OrderBy.Descending,
	}
}

func (sr *NonceSearchRequest) GetOrderBys() []searcher.OrderBy {
	orderBys := make([]searcher.OrderBy, len(sr.OrderBys))
	for i, value := range sr.OrderBys {
		orderBys[i] = searcher.OrderBy{
			Field:      value.Field,
			Descending: value.Descending,
		}
	}
	return orderBys
}

func (sr *NonceSearchRequest) GetLimit() int {
	return sr.Limit
}

func (sr *NonceSearchRequest) GetOffset() int {
	return sr.Offset
}

func (sr *NonceSearchRequest) IsSearchByID() bool {
	return sr.IsByID
}

func (sr *NonceSearchRequest) AddFilter(field NonceSearchField, value interface{}, operator searcher.FilterOperator, condition searcher.FilterCondition) {
	if len(sr.FilterGroup.Filters) > 0 || len(sr.FilterGroup.FilterGroups) > 0 {
		panic("Filters cannot be used with FilterGroups")
	}
	f := NonceSearchFilter{
		Field:     field,
		Value:     value,
		Operator:  operator,
		Condition: condition,
	}
	sr.Filters = append(sr.Filters, f)
}

func (sr *NonceSearchRequest) SetFilterGroup(fg searcher.FilterGroup) {
	if len(sr.Filters) > 0 {
		panic("FilterGroups cannot be used with Filters")
	}
	sr.FilterGroup = fg
}

func (sr *NonceSearchRequest) SetOrderBy(field NonceSearchField, isDescending bool) {
	sr.OrderBy = NonceOrderBy{
		Field:      field,
		Descending: isDescending,
	}

	// Set this primary order by as the first in the slice
	sr.OrderBys = []NonceOrderBy{sr.OrderBy}
}

func (sr *NonceSearchRequest) SetOrderBys(orderBys ...NonceOrderBy) {
	sr.OrderBys = append([]NonceOrderBy{}, orderBys...)
}

func (sr *NonceSearchRequest) GetAllFields() []string {
	return []string{
		"id",
		"shop_id",
		"nonce",
		"created_at",
		"updated_at",
	}
}

func (sr *NonceSearchRequest) GetFields() []string {
	fields := []string{}

	for _, f := range sr.Fields {
		fields = append(fields, f.DbFieldName())
	}

	return fields
}
