// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/searcher. DO NOT EDIT.

package search

import (
	"fmt"
	"strings"

	"github.com/getbread/breadkit/zeus/searcher"

	zeus "github.com/getbread/breadkit/zeus/types"
)

type SessionSearchField int

const (
	SessionSearch_Id SessionSearchField = iota
	SessionSearch_ShopId
	SessionSearch_Expiration
	SessionSearch_CreatedAt
	SessionSearch_UpdatedAt
)

func (s SessionSearchField) MarshalText() ([]byte, error) {
	var data string

	switch s {
	case SessionSearch_Id:
		data = "id"
	case SessionSearch_ShopId:
		data = "shop_id"
	case SessionSearch_Expiration:
		data = "expiration"
	case SessionSearch_CreatedAt:
		data = "createdAt"
	case SessionSearch_UpdatedAt:
		data = "updatedAt"

	default:
		return nil, fmt.Errorf("Cannot marshal text '%v'", s)
	}
	return []byte(data), nil
}

func (s SessionSearchField) MarshalBinary() ([]byte, error) {
	var data string

	switch s {
	case SessionSearch_Id:
		data = "id"
	case SessionSearch_ShopId:
		data = "shop_id"
	case SessionSearch_Expiration:
		data = "expiration"
	case SessionSearch_CreatedAt:
		data = "createdAt"
	case SessionSearch_UpdatedAt:
		data = "updatedAt"

	default:
		return nil, fmt.Errorf("Cannot marshal binary '%v'", s)
	}
	return []byte(data), nil
}

func (s *SessionSearchField) UnmarshalText(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "id":
		*s = SessionSearch_Id
	case "shop_id":
		*s = SessionSearch_ShopId
	case "expiration":
		*s = SessionSearch_Expiration
	case "createdAt":
		*s = SessionSearch_CreatedAt
	case "updatedAt":
		*s = SessionSearch_UpdatedAt

	default:
		return fmt.Errorf("Cannot unmarshal text '%s'", str)
	}
	return nil
}

func (s *SessionSearchField) UnmarshalBinary(b []byte) error {
	str := strings.Trim(string(b), `"`)

	switch str {
	case "id":
		*s = SessionSearch_Id
	case "shop_id":
		*s = SessionSearch_ShopId
	case "expiration":
		*s = SessionSearch_Expiration
	case "createdAt":
		*s = SessionSearch_CreatedAt
	case "updatedAt":
		*s = SessionSearch_UpdatedAt

	default:
		return fmt.Errorf("Cannot unmarshal binary '%s'", str)
	}
	return nil
}

func (s SessionSearchField) DbFieldName() string {
	switch s {
	case SessionSearch_Id:
		return "id"
	case SessionSearch_ShopId:
		return "shop_id"
	case SessionSearch_Expiration:
		return "expiration"
	case SessionSearch_CreatedAt:
		return "created_at"
	case SessionSearch_UpdatedAt:
		return "updated_at"

	}
	return ""
}

type SessionSearchRequest struct {
	searcher.SearchRequestFields

	Filters     []SessionSearchFilter `json:"filters"`
	FilterGroup searcher.FilterGroup  `json:"filterGroup"`
	OrderBy     SessionOrderBy        `json:"orderBy"`
	OrderBys    []SessionOrderBy      `json:"orderBys"`
	Fields      []SessionSearchField  `json:"fields"`
	IsByID      bool                  `json:"isById"`
}

type SessionSearchFilter struct {
	Field     SessionSearchField       `json:"field"`
	Value     interface{}              `json:"value"`
	Operator  searcher.FilterOperator  `json:"operator"`
	Condition searcher.FilterCondition `json:"condition"`
}

type SessionOrderBy struct {
	Field      SessionSearchField `json:"field"`
	Descending bool               `json:"desc"`
}

/*
SessionByID constructs a SessionSearchRequest to pull
a Session by it's ID.

You can add additional options using functions.

Handlers may choose to return (*Session, error) by checking the
IsSearchByID() function.
*/
func SessionByID(ID zeus.Uuid, options ...func(*SessionSearchRequest)) SessionSearchRequest {
	var searchRequest SessionSearchRequest

	searchRequest.AddFilter(
		SessionSearch_Id,
		ID,
		searcher.Operator_EQ,
		searcher.Condition_AND)

	searchRequest.Limit = 1
	searchRequest.IsByID = true

	for _, f := range options {
		f(&searchRequest)
	}

	return searchRequest
}

// implement searcher.SearchRequest interface
func (sr *SessionSearchRequest) GetTableName() string {
	return "shopify_shops_sessions"
}

func (sr *SessionSearchRequest) GetFilters() []searcher.Filter {
	filters := []searcher.Filter{}

	for _, f := range sr.Filters {
		filter := searcher.Filter{
			Field:     f.Field,
			Value:     f.Value,
			Operator:  f.Operator,
			Condition: f.Condition,
		}
		filters = append(filters, filter)
	}

	return filters
}

func (sr *SessionSearchRequest) GetFilterGroup() searcher.FilterGroup {
	return sr.FilterGroup
}

func (sr *SessionSearchRequest) GetOrderBy() searcher.OrderBy {
	return searcher.OrderBy{
		Field:      sr.OrderBy.Field,
		Descending: sr.OrderBy.Descending,
	}
}

func (sr *SessionSearchRequest) GetOrderBys() []searcher.OrderBy {
	orderBys := make([]searcher.OrderBy, len(sr.OrderBys))
	for i, value := range sr.OrderBys {
		orderBys[i] = searcher.OrderBy{
			Field:      value.Field,
			Descending: value.Descending,
		}
	}
	return orderBys
}

func (sr *SessionSearchRequest) GetLimit() int {
	return sr.Limit
}

func (sr *SessionSearchRequest) GetOffset() int {
	return sr.Offset
}

func (sr *SessionSearchRequest) IsSearchByID() bool {
	return sr.IsByID
}

func (sr *SessionSearchRequest) AddFilter(field SessionSearchField, value interface{}, operator searcher.FilterOperator, condition searcher.FilterCondition) {
	if len(sr.FilterGroup.Filters) > 0 || len(sr.FilterGroup.FilterGroups) > 0 {
		panic("Filters cannot be used with FilterGroups")
	}
	f := SessionSearchFilter{
		Field:     field,
		Value:     value,
		Operator:  operator,
		Condition: condition,
	}
	sr.Filters = append(sr.Filters, f)
}

func (sr *SessionSearchRequest) SetFilterGroup(fg searcher.FilterGroup) {
	if len(sr.Filters) > 0 {
		panic("FilterGroups cannot be used with Filters")
	}
	sr.FilterGroup = fg
}

func (sr *SessionSearchRequest) SetOrderBy(field SessionSearchField, isDescending bool) {
	sr.OrderBy = SessionOrderBy{
		Field:      field,
		Descending: isDescending,
	}

	// Set this primary order by as the first in the slice
	sr.OrderBys = []SessionOrderBy{sr.OrderBy}
}

func (sr *SessionSearchRequest) SetOrderBys(orderBys ...SessionOrderBy) {
	sr.OrderBys = append([]SessionOrderBy{}, orderBys...)
}

func (sr *SessionSearchRequest) GetAllFields() []string {
	return []string{
		"id",
		"shop_id",
		"expiration",
		"created_at",
		"updated_at",
	}
}

func (sr *SessionSearchRequest) GetFields() []string {
	fields := []string{}

	for _, f := range sr.Fields {
		fields = append(fields, f.DbFieldName())
	}

	return fields
}
