// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/searcher. DO NOT EDIT.

package dbhandlers

import (
	"errors"
	"fmt"
	"strings"

	"github.com/getbread/breadkit/zeus/searcher"
	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/jmoiron/sqlx"

	search "github.com/getbread/shopify_plugin_backend/service/search"
	types "github.com/getbread/shopify_plugin_backend/service/types"
)

// interface for this searcher
type AnalyticsOrderSearcher interface {
	Search(searchRequest search.AnalyticsOrderSearchRequest) ([]types.AnalyticsOrder, error)
	Count(searchRequest search.AnalyticsOrderSearchRequest) (searcher.CountResult, error)
	ById(id zeus.Uuid) (types.AnalyticsOrder, error)

	TxSearch(tx *sqlx.Tx, searchRequest search.AnalyticsOrderSearchRequest) ([]types.AnalyticsOrder, error)
	TxCount(tx *sqlx.Tx, searchRequest search.AnalyticsOrderSearchRequest) (searcher.CountResult, error)
	TxById(tx *sqlx.Tx, id zeus.Uuid) (types.AnalyticsOrder, error)
}

// implement SQL based searcher
type sqlAnalyticsOrderSearcher struct {
	db *sqlx.DB
}

func newSqlAnalyticsOrderSearcher(db *sqlx.DB) AnalyticsOrderSearcher {
	return &sqlAnalyticsOrderSearcher{db}
}

func NewSqlAnalyticsOrderSearcher(db *sqlx.DB) AnalyticsOrderSearcher {
	return &sqlAnalyticsOrderSearcher{db}
}

func (r *sqlAnalyticsOrderSearcher) Search(searchRequest search.AnalyticsOrderSearchRequest) ([]types.AnalyticsOrder, error) {
	results := []types.AnalyticsOrder{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for AnalyticsOrderSearcher : %s", err.Error())
	}

	err = r.db.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlAnalyticsOrderSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.AnalyticsOrderSearchRequest) ([]types.AnalyticsOrder, error) {
	results := []types.AnalyticsOrder{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for AnalyticsOrderSearcher : %s", err.Error())
	}

	err = tx.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlAnalyticsOrderSearcher) Count(searchRequest search.AnalyticsOrderSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for AnalyticsOrderSearcher : %s", err.Error())
	}

	err = r.db.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlAnalyticsOrderSearcher) TxCount(tx *sqlx.Tx, searchRequest search.AnalyticsOrderSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for AnalyticsOrderSearcher : %s", err.Error())
	}

	err = tx.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlAnalyticsOrderSearcher) ById(id zeus.Uuid) (types.AnalyticsOrder, error) {
	result := types.AnalyticsOrder{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.AnalyticsOrderSearchRequest{})

	err := r.db.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_analytics_orders WHERE id=$1", fieldsStr), string(id))

	return result, err
}

func (r *sqlAnalyticsOrderSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.AnalyticsOrder, error) {
	result := types.AnalyticsOrder{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.AnalyticsOrderSearchRequest{})

	err := tx.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_analytics_orders WHERE id=$1", fieldsStr), string(id))

	return result, err
}

// implement Fake searcher for testing
type FakeAnalyticsOrderSearcher struct {
	fakeResponse []types.AnalyticsOrder
	requests     []search.AnalyticsOrderSearchRequest

	fakeIdMap map[zeus.Uuid]types.AnalyticsOrder
	fakeError error

	// On the nth occurrence of a call to this searcher, return the slice, otherwise default to `fakeResponse`
	onOccurrenceReturns map[int][]types.AnalyticsOrder

	onOccurrenceCountReturns map[int]int
}

func NewFakeAnalyticsOrderSearcher(fakeResponse []types.AnalyticsOrder) AnalyticsOrderSearcher {
	return &FakeAnalyticsOrderSearcher{
		fakeResponse:             fakeResponse,
		requests:                 []search.AnalyticsOrderSearchRequest{},
		fakeIdMap:                map[zeus.Uuid]types.AnalyticsOrder{},
		fakeError:                nil,
		onOccurrenceReturns:      map[int][]types.AnalyticsOrder{},
		onOccurrenceCountReturns: map[int]int{},
	}
}

func (r *FakeAnalyticsOrderSearcher) Search(searchRequest search.AnalyticsOrderSearchRequest) ([]types.AnalyticsOrder, error) {
	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceReturns) > 0 {
		if occ, ok := r.onOccurrenceReturns[len(r.requests)]; ok {
			return occ, nil
		}
	}

	return r.fakeResponse, r.fakeError
}

func (r *FakeAnalyticsOrderSearcher) GetRequests() []search.AnalyticsOrderSearchRequest {
	return r.requests
}

func (r *FakeAnalyticsOrderSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.AnalyticsOrderSearchRequest) ([]types.AnalyticsOrder, error) {
	return r.Search(searchRequest)
}

func (r *FakeAnalyticsOrderSearcher) Count(searchRequest search.AnalyticsOrderSearchRequest) (searcher.CountResult, error) {
	count := searcher.CountResult{
		Count: len(r.fakeResponse),
	}

	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceCountReturns) > 0 {
		if occ, ok := r.onOccurrenceCountReturns[len(r.requests)]; ok {
			count.Count = occ
			return count, nil
		}
	}

	return count, r.fakeError
}

func (r *FakeAnalyticsOrderSearcher) TxCount(tx *sqlx.Tx, searchRequest search.AnalyticsOrderSearchRequest) (searcher.CountResult, error) {
	return r.Count(searchRequest)
}

func (r *FakeAnalyticsOrderSearcher) ById(id zeus.Uuid) (types.AnalyticsOrder, error) {
	if len(r.fakeIdMap) == 0 {
		return r.fakeResponse[0], nil
	}

	entity, ok := r.fakeIdMap[id]
	if !ok {
		return types.AnalyticsOrder{}, errors.New("Not able to find AnalyticsOrder by id: " + string(id))
	}

	return entity, r.fakeError
}

func (r *FakeAnalyticsOrderSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.AnalyticsOrder, error) {
	return r.ById(id)
}

func (r *FakeAnalyticsOrderSearcher) SetByIdResponses(resp map[zeus.Uuid]types.AnalyticsOrder) {
	r.fakeIdMap = resp
}

func (r *FakeAnalyticsOrderSearcher) SetError(err error) {
	r.fakeError = err
}

func (r *FakeAnalyticsOrderSearcher) GetFakeError() error {
	return r.fakeError
}

func (r *FakeAnalyticsOrderSearcher) GetOnOccurrenceReturns() map[int][]types.AnalyticsOrder {
	return r.onOccurrenceReturns
}

func (r *FakeAnalyticsOrderSearcher) SetOnOccurrenceReturns(val map[int][]types.AnalyticsOrder) {
	r.onOccurrenceReturns = val
}

func (r *FakeAnalyticsOrderSearcher) GetOnOccurrenceCountReturns() map[int]int {
	return r.onOccurrenceCountReturns
}

func (r *FakeAnalyticsOrderSearcher) SetOnOccurrenceCountReturns(val map[int]int) {
	r.onOccurrenceCountReturns = val
}
