// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package dbhandlers

import (
	"fmt"

	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/getbread/breadkit/zeus/updater"
	update "github.com/getbread/shopify_plugin_backend/service/update"
	"github.com/jmoiron/sqlx"
)

// interface for this updater
type AnalyticsOrderUpdater interface {
	Update(updateRequest update.AnalyticsOrderUpdateRequest) error
	TxUpdate(tx *sqlx.Tx, updateRequest update.AnalyticsOrderUpdateRequest) error
	DeleteById(id zeus.Uuid) error
	TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error
}

// implement SQL based updater
type sqlAnalyticsOrderUpdater struct {
	db *sqlx.DB
}

func newSqlAnalyticsOrderUpdater(db *sqlx.DB) AnalyticsOrderUpdater {
	return &sqlAnalyticsOrderUpdater{db: db}
}

func NewSqlAnalyticsOrderUpdater(db *sqlx.DB) AnalyticsOrderUpdater {
	return &sqlAnalyticsOrderUpdater{db: db}
}

func (r *sqlAnalyticsOrderUpdater) Update(updateRequest update.AnalyticsOrderUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for AnalyticsOrderUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlAnalyticsOrderUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.AnalyticsOrderUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for AnalyticsOrderUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlAnalyticsOrderUpdater) DeleteById(id zeus.Uuid) error {
	ur := update.AnalyticsOrderUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for AnalyticsOrderUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlAnalyticsOrderUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	ur := update.AnalyticsOrderUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for AnalyticsOrderUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

// implement Fake updater for testing
type FakeAnalyticsOrderUpdater struct {
	fakeResponse     error
	collectedUpdates []update.AnalyticsOrderUpdateRequest
	collectedDeletes []zeus.Uuid
}

func NewFakeAnalyticsOrderUpdater(fakeResponse error) AnalyticsOrderUpdater {
	return &FakeAnalyticsOrderUpdater{fakeResponse: fakeResponse}
}

func (r *FakeAnalyticsOrderUpdater) Update(updateRequest update.AnalyticsOrderUpdateRequest) error {
	r.collectedUpdates = append(r.collectedUpdates, updateRequest)
	return r.fakeResponse
}

func (r *FakeAnalyticsOrderUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.AnalyticsOrderUpdateRequest) error {
	return r.Update(updateRequest)
}

func (r *FakeAnalyticsOrderUpdater) DeleteById(id zeus.Uuid) error {
	r.collectedDeletes = append(r.collectedDeletes, id)
	return nil
}

func (r *FakeAnalyticsOrderUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	return r.DeleteById(id)
}

func (r *FakeAnalyticsOrderUpdater) GetCollectedUpdates() []update.AnalyticsOrderUpdateRequest {
	return r.collectedUpdates
}

func (r *FakeAnalyticsOrderUpdater) GetCollectedDeletes() []zeus.Uuid {
	return r.collectedDeletes
}
