// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package dbhandlers

import (
	"fmt"

	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/getbread/breadkit/zeus/updater"
	update "github.com/getbread/shopify_plugin_backend/service/update"
	"github.com/jmoiron/sqlx"
)

// interface for this updater
type DraftOrderCartUpdater interface {
	Update(updateRequest update.DraftOrderCartUpdateRequest) error
	TxUpdate(tx *sqlx.Tx, updateRequest update.DraftOrderCartUpdateRequest) error
	DeleteById(id zeus.Uuid) error
	TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error
}

// implement SQL based updater
type sqlDraftOrderCartUpdater struct {
	db *sqlx.DB
}

func newSqlDraftOrderCartUpdater(db *sqlx.DB) DraftOrderCartUpdater {
	return &sqlDraftOrderCartUpdater{db: db}
}

func NewSqlDraftOrderCartUpdater(db *sqlx.DB) DraftOrderCartUpdater {
	return &sqlDraftOrderCartUpdater{db: db}
}

func (r *sqlDraftOrderCartUpdater) Update(updateRequest update.DraftOrderCartUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for DraftOrderCartUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlDraftOrderCartUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.DraftOrderCartUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for DraftOrderCartUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlDraftOrderCartUpdater) DeleteById(id zeus.Uuid) error {
	ur := update.DraftOrderCartUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for DraftOrderCartUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlDraftOrderCartUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	ur := update.DraftOrderCartUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for DraftOrderCartUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

// implement Fake updater for testing
type FakeDraftOrderCartUpdater struct {
	fakeResponse     error
	collectedUpdates []update.DraftOrderCartUpdateRequest
	collectedDeletes []zeus.Uuid
}

func NewFakeDraftOrderCartUpdater(fakeResponse error) DraftOrderCartUpdater {
	return &FakeDraftOrderCartUpdater{fakeResponse: fakeResponse}
}

func (r *FakeDraftOrderCartUpdater) Update(updateRequest update.DraftOrderCartUpdateRequest) error {
	r.collectedUpdates = append(r.collectedUpdates, updateRequest)
	return r.fakeResponse
}

func (r *FakeDraftOrderCartUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.DraftOrderCartUpdateRequest) error {
	return r.Update(updateRequest)
}

func (r *FakeDraftOrderCartUpdater) DeleteById(id zeus.Uuid) error {
	r.collectedDeletes = append(r.collectedDeletes, id)
	return nil
}

func (r *FakeDraftOrderCartUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	return r.DeleteById(id)
}

func (r *FakeDraftOrderCartUpdater) GetCollectedUpdates() []update.DraftOrderCartUpdateRequest {
	return r.collectedUpdates
}

func (r *FakeDraftOrderCartUpdater) GetCollectedDeletes() []zeus.Uuid {
	return r.collectedDeletes
}
