// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package dbhandlers

import (
	"fmt"

	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/getbread/breadkit/zeus/updater"
	update "github.com/getbread/shopify_plugin_backend/service/update"
	"github.com/jmoiron/sqlx"
)

// interface for this updater
type DraftOrderCartCheckoutUpdater interface {
	Update(updateRequest update.DraftOrderCartCheckoutUpdateRequest) error
	TxUpdate(tx *sqlx.Tx, updateRequest update.DraftOrderCartCheckoutUpdateRequest) error
	DeleteById(id zeus.Uuid) error
	TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error
}

// implement SQL based updater
type sqlDraftOrderCartCheckoutUpdater struct {
	db *sqlx.DB
}

func newSqlDraftOrderCartCheckoutUpdater(db *sqlx.DB) DraftOrderCartCheckoutUpdater {
	return &sqlDraftOrderCartCheckoutUpdater{db: db}
}

func NewSqlDraftOrderCartCheckoutUpdater(db *sqlx.DB) DraftOrderCartCheckoutUpdater {
	return &sqlDraftOrderCartCheckoutUpdater{db: db}
}

func (r *sqlDraftOrderCartCheckoutUpdater) Update(updateRequest update.DraftOrderCartCheckoutUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for DraftOrderCartCheckoutUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlDraftOrderCartCheckoutUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.DraftOrderCartCheckoutUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for DraftOrderCartCheckoutUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlDraftOrderCartCheckoutUpdater) DeleteById(id zeus.Uuid) error {
	ur := update.DraftOrderCartCheckoutUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for DraftOrderCartCheckoutUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlDraftOrderCartCheckoutUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	ur := update.DraftOrderCartCheckoutUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for DraftOrderCartCheckoutUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

// implement Fake updater for testing
type FakeDraftOrderCartCheckoutUpdater struct {
	fakeResponse     error
	collectedUpdates []update.DraftOrderCartCheckoutUpdateRequest
	collectedDeletes []zeus.Uuid
}

func NewFakeDraftOrderCartCheckoutUpdater(fakeResponse error) DraftOrderCartCheckoutUpdater {
	return &FakeDraftOrderCartCheckoutUpdater{fakeResponse: fakeResponse}
}

func (r *FakeDraftOrderCartCheckoutUpdater) Update(updateRequest update.DraftOrderCartCheckoutUpdateRequest) error {
	r.collectedUpdates = append(r.collectedUpdates, updateRequest)
	return r.fakeResponse
}

func (r *FakeDraftOrderCartCheckoutUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.DraftOrderCartCheckoutUpdateRequest) error {
	return r.Update(updateRequest)
}

func (r *FakeDraftOrderCartCheckoutUpdater) DeleteById(id zeus.Uuid) error {
	r.collectedDeletes = append(r.collectedDeletes, id)
	return nil
}

func (r *FakeDraftOrderCartCheckoutUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	return r.DeleteById(id)
}

func (r *FakeDraftOrderCartCheckoutUpdater) GetCollectedUpdates() []update.DraftOrderCartCheckoutUpdateRequest {
	return r.collectedUpdates
}

func (r *FakeDraftOrderCartCheckoutUpdater) GetCollectedDeletes() []zeus.Uuid {
	return r.collectedDeletes
}
