// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/searcher. DO NOT EDIT.

package dbhandlers

import (
	"errors"
	"fmt"
	"strings"

	"github.com/getbread/breadkit/zeus/searcher"
	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/jmoiron/sqlx"

	search "github.com/getbread/shopify_plugin_backend/service/search"
	types "github.com/getbread/shopify_plugin_backend/service/types"
)

// interface for this searcher
type GatewayPasswordResetRequestSearcher interface {
	Search(searchRequest search.GatewayPasswordResetRequestSearchRequest) ([]types.GatewayPasswordResetRequest, error)
	Count(searchRequest search.GatewayPasswordResetRequestSearchRequest) (searcher.CountResult, error)
	ById(id zeus.Uuid) (types.GatewayPasswordResetRequest, error)

	TxSearch(tx *sqlx.Tx, searchRequest search.GatewayPasswordResetRequestSearchRequest) ([]types.GatewayPasswordResetRequest, error)
	TxCount(tx *sqlx.Tx, searchRequest search.GatewayPasswordResetRequestSearchRequest) (searcher.CountResult, error)
	TxById(tx *sqlx.Tx, id zeus.Uuid) (types.GatewayPasswordResetRequest, error)
}

// implement SQL based searcher
type sqlGatewayPasswordResetRequestSearcher struct {
	db *sqlx.DB
}

func newSqlGatewayPasswordResetRequestSearcher(db *sqlx.DB) GatewayPasswordResetRequestSearcher {
	return &sqlGatewayPasswordResetRequestSearcher{db}
}

func NewSqlGatewayPasswordResetRequestSearcher(db *sqlx.DB) GatewayPasswordResetRequestSearcher {
	return &sqlGatewayPasswordResetRequestSearcher{db}
}

func (r *sqlGatewayPasswordResetRequestSearcher) Search(searchRequest search.GatewayPasswordResetRequestSearchRequest) ([]types.GatewayPasswordResetRequest, error) {
	results := []types.GatewayPasswordResetRequest{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for GatewayPasswordResetRequestSearcher : %s", err.Error())
	}

	err = r.db.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlGatewayPasswordResetRequestSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.GatewayPasswordResetRequestSearchRequest) ([]types.GatewayPasswordResetRequest, error) {
	results := []types.GatewayPasswordResetRequest{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for GatewayPasswordResetRequestSearcher : %s", err.Error())
	}

	err = tx.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlGatewayPasswordResetRequestSearcher) Count(searchRequest search.GatewayPasswordResetRequestSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for GatewayPasswordResetRequestSearcher : %s", err.Error())
	}

	err = r.db.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlGatewayPasswordResetRequestSearcher) TxCount(tx *sqlx.Tx, searchRequest search.GatewayPasswordResetRequestSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for GatewayPasswordResetRequestSearcher : %s", err.Error())
	}

	err = tx.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlGatewayPasswordResetRequestSearcher) ById(id zeus.Uuid) (types.GatewayPasswordResetRequest, error) {
	result := types.GatewayPasswordResetRequest{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.GatewayPasswordResetRequestSearchRequest{})

	err := r.db.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_gateway_password_reset_requests WHERE id=$1", fieldsStr), string(id))

	return result, err
}

func (r *sqlGatewayPasswordResetRequestSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.GatewayPasswordResetRequest, error) {
	result := types.GatewayPasswordResetRequest{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.GatewayPasswordResetRequestSearchRequest{})

	err := tx.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_gateway_password_reset_requests WHERE id=$1", fieldsStr), string(id))

	return result, err
}

// implement Fake searcher for testing
type FakeGatewayPasswordResetRequestSearcher struct {
	fakeResponse []types.GatewayPasswordResetRequest
	requests     []search.GatewayPasswordResetRequestSearchRequest

	fakeIdMap map[zeus.Uuid]types.GatewayPasswordResetRequest
	fakeError error

	// On the nth occurrence of a call to this searcher, return the slice, otherwise default to `fakeResponse`
	onOccurrenceReturns map[int][]types.GatewayPasswordResetRequest

	onOccurrenceCountReturns map[int]int
}

func NewFakeGatewayPasswordResetRequestSearcher(fakeResponse []types.GatewayPasswordResetRequest) GatewayPasswordResetRequestSearcher {
	return &FakeGatewayPasswordResetRequestSearcher{
		fakeResponse:             fakeResponse,
		requests:                 []search.GatewayPasswordResetRequestSearchRequest{},
		fakeIdMap:                map[zeus.Uuid]types.GatewayPasswordResetRequest{},
		fakeError:                nil,
		onOccurrenceReturns:      map[int][]types.GatewayPasswordResetRequest{},
		onOccurrenceCountReturns: map[int]int{},
	}
}

func (r *FakeGatewayPasswordResetRequestSearcher) Search(searchRequest search.GatewayPasswordResetRequestSearchRequest) ([]types.GatewayPasswordResetRequest, error) {
	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceReturns) > 0 {
		if occ, ok := r.onOccurrenceReturns[len(r.requests)]; ok {
			return occ, nil
		}
	}

	return r.fakeResponse, r.fakeError
}

func (r *FakeGatewayPasswordResetRequestSearcher) GetRequests() []search.GatewayPasswordResetRequestSearchRequest {
	return r.requests
}

func (r *FakeGatewayPasswordResetRequestSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.GatewayPasswordResetRequestSearchRequest) ([]types.GatewayPasswordResetRequest, error) {
	return r.Search(searchRequest)
}

func (r *FakeGatewayPasswordResetRequestSearcher) Count(searchRequest search.GatewayPasswordResetRequestSearchRequest) (searcher.CountResult, error) {
	count := searcher.CountResult{
		Count: len(r.fakeResponse),
	}

	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceCountReturns) > 0 {
		if occ, ok := r.onOccurrenceCountReturns[len(r.requests)]; ok {
			count.Count = occ
			return count, nil
		}
	}

	return count, r.fakeError
}

func (r *FakeGatewayPasswordResetRequestSearcher) TxCount(tx *sqlx.Tx, searchRequest search.GatewayPasswordResetRequestSearchRequest) (searcher.CountResult, error) {
	return r.Count(searchRequest)
}

func (r *FakeGatewayPasswordResetRequestSearcher) ById(id zeus.Uuid) (types.GatewayPasswordResetRequest, error) {
	if len(r.fakeIdMap) == 0 {
		return r.fakeResponse[0], nil
	}

	entity, ok := r.fakeIdMap[id]
	if !ok {
		return types.GatewayPasswordResetRequest{}, errors.New("Not able to find GatewayPasswordResetRequest by id: " + string(id))
	}

	return entity, r.fakeError
}

func (r *FakeGatewayPasswordResetRequestSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.GatewayPasswordResetRequest, error) {
	return r.ById(id)
}

func (r *FakeGatewayPasswordResetRequestSearcher) SetByIdResponses(resp map[zeus.Uuid]types.GatewayPasswordResetRequest) {
	r.fakeIdMap = resp
}

func (r *FakeGatewayPasswordResetRequestSearcher) SetError(err error) {
	r.fakeError = err
}

func (r *FakeGatewayPasswordResetRequestSearcher) GetFakeError() error {
	return r.fakeError
}

func (r *FakeGatewayPasswordResetRequestSearcher) GetOnOccurrenceReturns() map[int][]types.GatewayPasswordResetRequest {
	return r.onOccurrenceReturns
}

func (r *FakeGatewayPasswordResetRequestSearcher) SetOnOccurrenceReturns(val map[int][]types.GatewayPasswordResetRequest) {
	r.onOccurrenceReturns = val
}

func (r *FakeGatewayPasswordResetRequestSearcher) GetOnOccurrenceCountReturns() map[int]int {
	return r.onOccurrenceCountReturns
}

func (r *FakeGatewayPasswordResetRequestSearcher) SetOnOccurrenceCountReturns(val map[int]int) {
	r.onOccurrenceCountReturns = val
}
