// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package dbhandlers

import (
	"fmt"

	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/getbread/breadkit/zeus/updater"
	update "github.com/getbread/shopify_plugin_backend/service/update"
	"github.com/jmoiron/sqlx"
)

// interface for this updater
type GatewayPasswordResetRequestUpdater interface {
	Update(updateRequest update.GatewayPasswordResetRequestUpdateRequest) error
	TxUpdate(tx *sqlx.Tx, updateRequest update.GatewayPasswordResetRequestUpdateRequest) error
	DeleteById(id zeus.Uuid) error
	TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error
}

// implement SQL based updater
type sqlGatewayPasswordResetRequestUpdater struct {
	db *sqlx.DB
}

func newSqlGatewayPasswordResetRequestUpdater(db *sqlx.DB) GatewayPasswordResetRequestUpdater {
	return &sqlGatewayPasswordResetRequestUpdater{db: db}
}

func NewSqlGatewayPasswordResetRequestUpdater(db *sqlx.DB) GatewayPasswordResetRequestUpdater {
	return &sqlGatewayPasswordResetRequestUpdater{db: db}
}

func (r *sqlGatewayPasswordResetRequestUpdater) Update(updateRequest update.GatewayPasswordResetRequestUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for GatewayPasswordResetRequestUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlGatewayPasswordResetRequestUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.GatewayPasswordResetRequestUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for GatewayPasswordResetRequestUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlGatewayPasswordResetRequestUpdater) DeleteById(id zeus.Uuid) error {
	ur := update.GatewayPasswordResetRequestUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for GatewayPasswordResetRequestUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlGatewayPasswordResetRequestUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	ur := update.GatewayPasswordResetRequestUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for GatewayPasswordResetRequestUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

// implement Fake updater for testing
type FakeGatewayPasswordResetRequestUpdater struct {
	fakeResponse     error
	collectedUpdates []update.GatewayPasswordResetRequestUpdateRequest
	collectedDeletes []zeus.Uuid
}

func NewFakeGatewayPasswordResetRequestUpdater(fakeResponse error) GatewayPasswordResetRequestUpdater {
	return &FakeGatewayPasswordResetRequestUpdater{fakeResponse: fakeResponse}
}

func (r *FakeGatewayPasswordResetRequestUpdater) Update(updateRequest update.GatewayPasswordResetRequestUpdateRequest) error {
	r.collectedUpdates = append(r.collectedUpdates, updateRequest)
	return r.fakeResponse
}

func (r *FakeGatewayPasswordResetRequestUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.GatewayPasswordResetRequestUpdateRequest) error {
	return r.Update(updateRequest)
}

func (r *FakeGatewayPasswordResetRequestUpdater) DeleteById(id zeus.Uuid) error {
	r.collectedDeletes = append(r.collectedDeletes, id)
	return nil
}

func (r *FakeGatewayPasswordResetRequestUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	return r.DeleteById(id)
}

func (r *FakeGatewayPasswordResetRequestUpdater) GetCollectedUpdates() []update.GatewayPasswordResetRequestUpdateRequest {
	return r.collectedUpdates
}

func (r *FakeGatewayPasswordResetRequestUpdater) GetCollectedDeletes() []zeus.Uuid {
	return r.collectedDeletes
}
