// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package dbhandlers

import (
	"fmt"

	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/getbread/breadkit/zeus/updater"
	update "github.com/getbread/shopify_plugin_backend/service/update"
	"github.com/jmoiron/sqlx"
)

// interface for this updater
type GatewayCheckoutUpdater interface {
	Update(updateRequest update.GatewayCheckoutUpdateRequest) error
	TxUpdate(tx *sqlx.Tx, updateRequest update.GatewayCheckoutUpdateRequest) error
	DeleteById(id zeus.Uuid) error
	TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error
}

// implement SQL based updater
type sqlGatewayCheckoutUpdater struct {
	db *sqlx.DB
}

func newSqlGatewayCheckoutUpdater(db *sqlx.DB) GatewayCheckoutUpdater {
	return &sqlGatewayCheckoutUpdater{db: db}
}

func NewSqlGatewayCheckoutUpdater(db *sqlx.DB) GatewayCheckoutUpdater {
	return &sqlGatewayCheckoutUpdater{db: db}
}

func (r *sqlGatewayCheckoutUpdater) Update(updateRequest update.GatewayCheckoutUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for GatewayCheckoutUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlGatewayCheckoutUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.GatewayCheckoutUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for GatewayCheckoutUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlGatewayCheckoutUpdater) DeleteById(id zeus.Uuid) error {
	ur := update.GatewayCheckoutUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for GatewayCheckoutUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlGatewayCheckoutUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	ur := update.GatewayCheckoutUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for GatewayCheckoutUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

// implement Fake updater for testing
type FakeGatewayCheckoutUpdater struct {
	fakeResponse     error
	collectedUpdates []update.GatewayCheckoutUpdateRequest
	collectedDeletes []zeus.Uuid
}

func NewFakeGatewayCheckoutUpdater(fakeResponse error) GatewayCheckoutUpdater {
	return &FakeGatewayCheckoutUpdater{fakeResponse: fakeResponse}
}

func (r *FakeGatewayCheckoutUpdater) Update(updateRequest update.GatewayCheckoutUpdateRequest) error {
	r.collectedUpdates = append(r.collectedUpdates, updateRequest)
	return r.fakeResponse
}

func (r *FakeGatewayCheckoutUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.GatewayCheckoutUpdateRequest) error {
	return r.Update(updateRequest)
}

func (r *FakeGatewayCheckoutUpdater) DeleteById(id zeus.Uuid) error {
	r.collectedDeletes = append(r.collectedDeletes, id)
	return nil
}

func (r *FakeGatewayCheckoutUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	return r.DeleteById(id)
}

func (r *FakeGatewayCheckoutUpdater) GetCollectedUpdates() []update.GatewayCheckoutUpdateRequest {
	return r.collectedUpdates
}

func (r *FakeGatewayCheckoutUpdater) GetCollectedDeletes() []zeus.Uuid {
	return r.collectedDeletes
}
