// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/searcher. DO NOT EDIT.

package dbhandlers

import (
	"errors"
	"fmt"
	"strings"

	"github.com/getbread/breadkit/zeus/searcher"
	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/jmoiron/sqlx"

	search "github.com/getbread/shopify_plugin_backend/service/search"
	types "github.com/getbread/shopify_plugin_backend/service/types"
)

// interface for this searcher
type GatewayCheckoutSearcher interface {
	Search(searchRequest search.GatewayCheckoutSearchRequest) ([]types.GatewayCheckout, error)
	Count(searchRequest search.GatewayCheckoutSearchRequest) (searcher.CountResult, error)
	ById(id zeus.Uuid) (types.GatewayCheckout, error)

	TxSearch(tx *sqlx.Tx, searchRequest search.GatewayCheckoutSearchRequest) ([]types.GatewayCheckout, error)
	TxCount(tx *sqlx.Tx, searchRequest search.GatewayCheckoutSearchRequest) (searcher.CountResult, error)
	TxById(tx *sqlx.Tx, id zeus.Uuid) (types.GatewayCheckout, error)
}

// implement SQL based searcher
type sqlGatewayCheckoutSearcher struct {
	db *sqlx.DB
}

func newSqlGatewayCheckoutSearcher(db *sqlx.DB) GatewayCheckoutSearcher {
	return &sqlGatewayCheckoutSearcher{db}
}

func NewSqlGatewayCheckoutSearcher(db *sqlx.DB) GatewayCheckoutSearcher {
	return &sqlGatewayCheckoutSearcher{db}
}

func (r *sqlGatewayCheckoutSearcher) Search(searchRequest search.GatewayCheckoutSearchRequest) ([]types.GatewayCheckout, error) {
	results := []types.GatewayCheckout{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for GatewayCheckoutSearcher : %s", err.Error())
	}

	err = r.db.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlGatewayCheckoutSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.GatewayCheckoutSearchRequest) ([]types.GatewayCheckout, error) {
	results := []types.GatewayCheckout{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for GatewayCheckoutSearcher : %s", err.Error())
	}

	err = tx.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlGatewayCheckoutSearcher) Count(searchRequest search.GatewayCheckoutSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for GatewayCheckoutSearcher : %s", err.Error())
	}

	err = r.db.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlGatewayCheckoutSearcher) TxCount(tx *sqlx.Tx, searchRequest search.GatewayCheckoutSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for GatewayCheckoutSearcher : %s", err.Error())
	}

	err = tx.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlGatewayCheckoutSearcher) ById(id zeus.Uuid) (types.GatewayCheckout, error) {
	result := types.GatewayCheckout{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.GatewayCheckoutSearchRequest{})

	err := r.db.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_gateway_checkouts WHERE id=$1", fieldsStr), string(id))

	return result, err
}

func (r *sqlGatewayCheckoutSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.GatewayCheckout, error) {
	result := types.GatewayCheckout{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.GatewayCheckoutSearchRequest{})

	err := tx.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_gateway_checkouts WHERE id=$1", fieldsStr), string(id))

	return result, err
}

// implement Fake searcher for testing
type FakeGatewayCheckoutSearcher struct {
	fakeResponse []types.GatewayCheckout
	requests     []search.GatewayCheckoutSearchRequest

	fakeIdMap map[zeus.Uuid]types.GatewayCheckout
	fakeError error

	// On the nth occurrence of a call to this searcher, return the slice, otherwise default to `fakeResponse`
	onOccurrenceReturns map[int][]types.GatewayCheckout

	onOccurrenceCountReturns map[int]int
}

func NewFakeGatewayCheckoutSearcher(fakeResponse []types.GatewayCheckout) GatewayCheckoutSearcher {
	return &FakeGatewayCheckoutSearcher{
		fakeResponse:             fakeResponse,
		requests:                 []search.GatewayCheckoutSearchRequest{},
		fakeIdMap:                map[zeus.Uuid]types.GatewayCheckout{},
		fakeError:                nil,
		onOccurrenceReturns:      map[int][]types.GatewayCheckout{},
		onOccurrenceCountReturns: map[int]int{},
	}
}

func (r *FakeGatewayCheckoutSearcher) Search(searchRequest search.GatewayCheckoutSearchRequest) ([]types.GatewayCheckout, error) {
	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceReturns) > 0 {
		if occ, ok := r.onOccurrenceReturns[len(r.requests)]; ok {
			return occ, nil
		}
	}

	return r.fakeResponse, r.fakeError
}

func (r *FakeGatewayCheckoutSearcher) GetRequests() []search.GatewayCheckoutSearchRequest {
	return r.requests
}

func (r *FakeGatewayCheckoutSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.GatewayCheckoutSearchRequest) ([]types.GatewayCheckout, error) {
	return r.Search(searchRequest)
}

func (r *FakeGatewayCheckoutSearcher) Count(searchRequest search.GatewayCheckoutSearchRequest) (searcher.CountResult, error) {
	count := searcher.CountResult{
		Count: len(r.fakeResponse),
	}

	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceCountReturns) > 0 {
		if occ, ok := r.onOccurrenceCountReturns[len(r.requests)]; ok {
			count.Count = occ
			return count, nil
		}
	}

	return count, r.fakeError
}

func (r *FakeGatewayCheckoutSearcher) TxCount(tx *sqlx.Tx, searchRequest search.GatewayCheckoutSearchRequest) (searcher.CountResult, error) {
	return r.Count(searchRequest)
}

func (r *FakeGatewayCheckoutSearcher) ById(id zeus.Uuid) (types.GatewayCheckout, error) {
	if len(r.fakeIdMap) == 0 {
		return r.fakeResponse[0], nil
	}

	entity, ok := r.fakeIdMap[id]
	if !ok {
		return types.GatewayCheckout{}, errors.New("Not able to find GatewayCheckout by id: " + string(id))
	}

	return entity, r.fakeError
}

func (r *FakeGatewayCheckoutSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.GatewayCheckout, error) {
	return r.ById(id)
}

func (r *FakeGatewayCheckoutSearcher) SetByIdResponses(resp map[zeus.Uuid]types.GatewayCheckout) {
	r.fakeIdMap = resp
}

func (r *FakeGatewayCheckoutSearcher) SetError(err error) {
	r.fakeError = err
}

func (r *FakeGatewayCheckoutSearcher) GetFakeError() error {
	return r.fakeError
}

func (r *FakeGatewayCheckoutSearcher) GetOnOccurrenceReturns() map[int][]types.GatewayCheckout {
	return r.onOccurrenceReturns
}

func (r *FakeGatewayCheckoutSearcher) SetOnOccurrenceReturns(val map[int][]types.GatewayCheckout) {
	r.onOccurrenceReturns = val
}

func (r *FakeGatewayCheckoutSearcher) GetOnOccurrenceCountReturns() map[int]int {
	return r.onOccurrenceCountReturns
}

func (r *FakeGatewayCheckoutSearcher) SetOnOccurrenceCountReturns(val map[int]int) {
	r.onOccurrenceCountReturns = val
}
