// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package dbhandlers

import (
	"fmt"

	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/getbread/breadkit/zeus/updater"
	update "github.com/getbread/shopify_plugin_backend/service/update"
	"github.com/jmoiron/sqlx"
)

// interface for this updater
type GatewaySessionUpdater interface {
	Update(updateRequest update.GatewaySessionUpdateRequest) error
	TxUpdate(tx *sqlx.Tx, updateRequest update.GatewaySessionUpdateRequest) error
	DeleteById(id zeus.Uuid) error
	TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error
}

// implement SQL based updater
type sqlGatewaySessionUpdater struct {
	db *sqlx.DB
}

func newSqlGatewaySessionUpdater(db *sqlx.DB) GatewaySessionUpdater {
	return &sqlGatewaySessionUpdater{db: db}
}

func NewSqlGatewaySessionUpdater(db *sqlx.DB) GatewaySessionUpdater {
	return &sqlGatewaySessionUpdater{db: db}
}

func (r *sqlGatewaySessionUpdater) Update(updateRequest update.GatewaySessionUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for GatewaySessionUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlGatewaySessionUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.GatewaySessionUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for GatewaySessionUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlGatewaySessionUpdater) DeleteById(id zeus.Uuid) error {
	ur := update.GatewaySessionUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for GatewaySessionUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlGatewaySessionUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	ur := update.GatewaySessionUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for GatewaySessionUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

// implement Fake updater for testing
type FakeGatewaySessionUpdater struct {
	fakeResponse     error
	collectedUpdates []update.GatewaySessionUpdateRequest
	collectedDeletes []zeus.Uuid
}

func NewFakeGatewaySessionUpdater(fakeResponse error) GatewaySessionUpdater {
	return &FakeGatewaySessionUpdater{fakeResponse: fakeResponse}
}

func (r *FakeGatewaySessionUpdater) Update(updateRequest update.GatewaySessionUpdateRequest) error {
	r.collectedUpdates = append(r.collectedUpdates, updateRequest)
	return r.fakeResponse
}

func (r *FakeGatewaySessionUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.GatewaySessionUpdateRequest) error {
	return r.Update(updateRequest)
}

func (r *FakeGatewaySessionUpdater) DeleteById(id zeus.Uuid) error {
	r.collectedDeletes = append(r.collectedDeletes, id)
	return nil
}

func (r *FakeGatewaySessionUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	return r.DeleteById(id)
}

func (r *FakeGatewaySessionUpdater) GetCollectedUpdates() []update.GatewaySessionUpdateRequest {
	return r.collectedUpdates
}

func (r *FakeGatewaySessionUpdater) GetCollectedDeletes() []zeus.Uuid {
	return r.collectedDeletes
}
