// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package dbhandlers

import (
	"fmt"

	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/getbread/breadkit/zeus/updater"
	update "github.com/getbread/shopify_plugin_backend/service/update"
	"github.com/jmoiron/sqlx"
)

// interface for this updater
type GatewayAccountUpdater interface {
	Update(updateRequest update.GatewayAccountUpdateRequest) error
	TxUpdate(tx *sqlx.Tx, updateRequest update.GatewayAccountUpdateRequest) error
	DeleteById(id zeus.Uuid) error
	TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error
}

// implement SQL based updater
type sqlGatewayAccountUpdater struct {
	db *sqlx.DB
}

func newSqlGatewayAccountUpdater(db *sqlx.DB) GatewayAccountUpdater {
	return &sqlGatewayAccountUpdater{db: db}
}

func NewSqlGatewayAccountUpdater(db *sqlx.DB) GatewayAccountUpdater {
	return &sqlGatewayAccountUpdater{db: db}
}

func (r *sqlGatewayAccountUpdater) Update(updateRequest update.GatewayAccountUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for GatewayAccountUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlGatewayAccountUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.GatewayAccountUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for GatewayAccountUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlGatewayAccountUpdater) DeleteById(id zeus.Uuid) error {
	ur := update.GatewayAccountUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for GatewayAccountUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlGatewayAccountUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	ur := update.GatewayAccountUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for GatewayAccountUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

// implement Fake updater for testing
type FakeGatewayAccountUpdater struct {
	fakeResponse     error
	collectedUpdates []update.GatewayAccountUpdateRequest
	collectedDeletes []zeus.Uuid
}

func NewFakeGatewayAccountUpdater(fakeResponse error) GatewayAccountUpdater {
	return &FakeGatewayAccountUpdater{fakeResponse: fakeResponse}
}

func (r *FakeGatewayAccountUpdater) Update(updateRequest update.GatewayAccountUpdateRequest) error {
	r.collectedUpdates = append(r.collectedUpdates, updateRequest)
	return r.fakeResponse
}

func (r *FakeGatewayAccountUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.GatewayAccountUpdateRequest) error {
	return r.Update(updateRequest)
}

func (r *FakeGatewayAccountUpdater) DeleteById(id zeus.Uuid) error {
	r.collectedDeletes = append(r.collectedDeletes, id)
	return nil
}

func (r *FakeGatewayAccountUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	return r.DeleteById(id)
}

func (r *FakeGatewayAccountUpdater) GetCollectedUpdates() []update.GatewayAccountUpdateRequest {
	return r.collectedUpdates
}

func (r *FakeGatewayAccountUpdater) GetCollectedDeletes() []zeus.Uuid {
	return r.collectedDeletes
}
