// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/searcher. DO NOT EDIT.

package dbhandlers

import (
	"errors"
	"fmt"
	"strings"

	"github.com/getbread/breadkit/zeus/searcher"
	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/jmoiron/sqlx"

	search "github.com/getbread/shopify_plugin_backend/service/search"
	types "github.com/getbread/shopify_plugin_backend/service/types"
)

// interface for this searcher
type GiftCardOrderSearcher interface {
	Search(searchRequest search.GiftCardOrderSearchRequest) ([]types.GiftCardOrder, error)
	Count(searchRequest search.GiftCardOrderSearchRequest) (searcher.CountResult, error)
	ById(id zeus.Uuid) (types.GiftCardOrder, error)

	TxSearch(tx *sqlx.Tx, searchRequest search.GiftCardOrderSearchRequest) ([]types.GiftCardOrder, error)
	TxCount(tx *sqlx.Tx, searchRequest search.GiftCardOrderSearchRequest) (searcher.CountResult, error)
	TxById(tx *sqlx.Tx, id zeus.Uuid) (types.GiftCardOrder, error)
}

// implement SQL based searcher
type sqlGiftCardOrderSearcher struct {
	db *sqlx.DB
}

func newSqlGiftCardOrderSearcher(db *sqlx.DB) GiftCardOrderSearcher {
	return &sqlGiftCardOrderSearcher{db}
}

func NewSqlGiftCardOrderSearcher(db *sqlx.DB) GiftCardOrderSearcher {
	return &sqlGiftCardOrderSearcher{db}
}

func (r *sqlGiftCardOrderSearcher) Search(searchRequest search.GiftCardOrderSearchRequest) ([]types.GiftCardOrder, error) {
	results := []types.GiftCardOrder{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for GiftCardOrderSearcher : %s", err.Error())
	}

	err = r.db.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlGiftCardOrderSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.GiftCardOrderSearchRequest) ([]types.GiftCardOrder, error) {
	results := []types.GiftCardOrder{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for GiftCardOrderSearcher : %s", err.Error())
	}

	err = tx.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlGiftCardOrderSearcher) Count(searchRequest search.GiftCardOrderSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for GiftCardOrderSearcher : %s", err.Error())
	}

	err = r.db.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlGiftCardOrderSearcher) TxCount(tx *sqlx.Tx, searchRequest search.GiftCardOrderSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for GiftCardOrderSearcher : %s", err.Error())
	}

	err = tx.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlGiftCardOrderSearcher) ById(id zeus.Uuid) (types.GiftCardOrder, error) {
	result := types.GiftCardOrder{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.GiftCardOrderSearchRequest{})

	err := r.db.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_gift_card_orders WHERE id=$1", fieldsStr), string(id))

	return result, err
}

func (r *sqlGiftCardOrderSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.GiftCardOrder, error) {
	result := types.GiftCardOrder{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.GiftCardOrderSearchRequest{})

	err := tx.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_gift_card_orders WHERE id=$1", fieldsStr), string(id))

	return result, err
}

// implement Fake searcher for testing
type FakeGiftCardOrderSearcher struct {
	fakeResponse []types.GiftCardOrder
	requests     []search.GiftCardOrderSearchRequest

	fakeIdMap map[zeus.Uuid]types.GiftCardOrder
	fakeError error

	// On the nth occurrence of a call to this searcher, return the slice, otherwise default to `fakeResponse`
	onOccurrenceReturns map[int][]types.GiftCardOrder

	onOccurrenceCountReturns map[int]int
}

func NewFakeGiftCardOrderSearcher(fakeResponse []types.GiftCardOrder) GiftCardOrderSearcher {
	return &FakeGiftCardOrderSearcher{
		fakeResponse:             fakeResponse,
		requests:                 []search.GiftCardOrderSearchRequest{},
		fakeIdMap:                map[zeus.Uuid]types.GiftCardOrder{},
		fakeError:                nil,
		onOccurrenceReturns:      map[int][]types.GiftCardOrder{},
		onOccurrenceCountReturns: map[int]int{},
	}
}

func (r *FakeGiftCardOrderSearcher) Search(searchRequest search.GiftCardOrderSearchRequest) ([]types.GiftCardOrder, error) {
	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceReturns) > 0 {
		if occ, ok := r.onOccurrenceReturns[len(r.requests)]; ok {
			return occ, nil
		}
	}

	return r.fakeResponse, r.fakeError
}

func (r *FakeGiftCardOrderSearcher) GetRequests() []search.GiftCardOrderSearchRequest {
	return r.requests
}

func (r *FakeGiftCardOrderSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.GiftCardOrderSearchRequest) ([]types.GiftCardOrder, error) {
	return r.Search(searchRequest)
}

func (r *FakeGiftCardOrderSearcher) Count(searchRequest search.GiftCardOrderSearchRequest) (searcher.CountResult, error) {
	count := searcher.CountResult{
		Count: len(r.fakeResponse),
	}

	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceCountReturns) > 0 {
		if occ, ok := r.onOccurrenceCountReturns[len(r.requests)]; ok {
			count.Count = occ
			return count, nil
		}
	}

	return count, r.fakeError
}

func (r *FakeGiftCardOrderSearcher) TxCount(tx *sqlx.Tx, searchRequest search.GiftCardOrderSearchRequest) (searcher.CountResult, error) {
	return r.Count(searchRequest)
}

func (r *FakeGiftCardOrderSearcher) ById(id zeus.Uuid) (types.GiftCardOrder, error) {
	if len(r.fakeIdMap) == 0 {
		return r.fakeResponse[0], nil
	}

	entity, ok := r.fakeIdMap[id]
	if !ok {
		return types.GiftCardOrder{}, errors.New("Not able to find GiftCardOrder by id: " + string(id))
	}

	return entity, r.fakeError
}

func (r *FakeGiftCardOrderSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.GiftCardOrder, error) {
	return r.ById(id)
}

func (r *FakeGiftCardOrderSearcher) SetByIdResponses(resp map[zeus.Uuid]types.GiftCardOrder) {
	r.fakeIdMap = resp
}

func (r *FakeGiftCardOrderSearcher) SetError(err error) {
	r.fakeError = err
}

func (r *FakeGiftCardOrderSearcher) GetFakeError() error {
	return r.fakeError
}

func (r *FakeGiftCardOrderSearcher) GetOnOccurrenceReturns() map[int][]types.GiftCardOrder {
	return r.onOccurrenceReturns
}

func (r *FakeGiftCardOrderSearcher) SetOnOccurrenceReturns(val map[int][]types.GiftCardOrder) {
	r.onOccurrenceReturns = val
}

func (r *FakeGiftCardOrderSearcher) GetOnOccurrenceCountReturns() map[int]int {
	return r.onOccurrenceCountReturns
}

func (r *FakeGiftCardOrderSearcher) SetOnOccurrenceCountReturns(val map[int]int) {
	r.onOccurrenceCountReturns = val
}
