// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package dbhandlers

import (
	"fmt"

	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/getbread/breadkit/zeus/updater"
	update "github.com/getbread/shopify_plugin_backend/service/update"
	"github.com/jmoiron/sqlx"
)

// interface for this updater
type NonceUpdater interface {
	Update(updateRequest update.NonceUpdateRequest) error
	TxUpdate(tx *sqlx.Tx, updateRequest update.NonceUpdateRequest) error
	DeleteById(id zeus.Uuid) error
	TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error
}

// implement SQL based updater
type sqlNonceUpdater struct {
	db *sqlx.DB
}

func newSqlNonceUpdater(db *sqlx.DB) NonceUpdater {
	return &sqlNonceUpdater{db: db}
}

func NewSqlNonceUpdater(db *sqlx.DB) NonceUpdater {
	return &sqlNonceUpdater{db: db}
}

func (r *sqlNonceUpdater) Update(updateRequest update.NonceUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for NonceUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlNonceUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.NonceUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for NonceUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlNonceUpdater) DeleteById(id zeus.Uuid) error {
	ur := update.NonceUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for NonceUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlNonceUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	ur := update.NonceUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for NonceUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

// implement Fake updater for testing
type FakeNonceUpdater struct {
	fakeResponse     error
	collectedUpdates []update.NonceUpdateRequest
	collectedDeletes []zeus.Uuid
}

func NewFakeNonceUpdater(fakeResponse error) NonceUpdater {
	return &FakeNonceUpdater{fakeResponse: fakeResponse}
}

func (r *FakeNonceUpdater) Update(updateRequest update.NonceUpdateRequest) error {
	r.collectedUpdates = append(r.collectedUpdates, updateRequest)
	return r.fakeResponse
}

func (r *FakeNonceUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.NonceUpdateRequest) error {
	return r.Update(updateRequest)
}

func (r *FakeNonceUpdater) DeleteById(id zeus.Uuid) error {
	r.collectedDeletes = append(r.collectedDeletes, id)
	return nil
}

func (r *FakeNonceUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	return r.DeleteById(id)
}

func (r *FakeNonceUpdater) GetCollectedUpdates() []update.NonceUpdateRequest {
	return r.collectedUpdates
}

func (r *FakeNonceUpdater) GetCollectedDeletes() []zeus.Uuid {
	return r.collectedDeletes
}
