// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/searcher. DO NOT EDIT.

package dbhandlers

import (
	"errors"
	"fmt"
	"strings"

	"github.com/getbread/breadkit/zeus/searcher"
	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/jmoiron/sqlx"

	search "github.com/getbread/shopify_plugin_backend/service/search"
	types "github.com/getbread/shopify_plugin_backend/service/types"
)

// interface for this searcher
type OrderSearcher interface {
	Search(searchRequest search.OrderSearchRequest) ([]types.Order, error)
	Count(searchRequest search.OrderSearchRequest) (searcher.CountResult, error)
	ById(id zeus.Uuid) (types.Order, error)

	TxSearch(tx *sqlx.Tx, searchRequest search.OrderSearchRequest) ([]types.Order, error)
	TxCount(tx *sqlx.Tx, searchRequest search.OrderSearchRequest) (searcher.CountResult, error)
	TxById(tx *sqlx.Tx, id zeus.Uuid) (types.Order, error)
}

// implement SQL based searcher
type sqlOrderSearcher struct {
	db *sqlx.DB
}

func newSqlOrderSearcher(db *sqlx.DB) OrderSearcher {
	return &sqlOrderSearcher{db}
}

func NewSqlOrderSearcher(db *sqlx.DB) OrderSearcher {
	return &sqlOrderSearcher{db}
}

func (r *sqlOrderSearcher) Search(searchRequest search.OrderSearchRequest) ([]types.Order, error) {
	results := []types.Order{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for OrderSearcher : %s", err.Error())
	}

	err = r.db.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlOrderSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.OrderSearchRequest) ([]types.Order, error) {
	results := []types.Order{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for OrderSearcher : %s", err.Error())
	}

	err = tx.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlOrderSearcher) Count(searchRequest search.OrderSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for OrderSearcher : %s", err.Error())
	}

	err = r.db.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlOrderSearcher) TxCount(tx *sqlx.Tx, searchRequest search.OrderSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for OrderSearcher : %s", err.Error())
	}

	err = tx.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlOrderSearcher) ById(id zeus.Uuid) (types.Order, error) {
	result := types.Order{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.OrderSearchRequest{})

	err := r.db.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_shops_orders WHERE id=$1", fieldsStr), string(id))

	return result, err
}

func (r *sqlOrderSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.Order, error) {
	result := types.Order{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.OrderSearchRequest{})

	err := tx.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_shops_orders WHERE id=$1", fieldsStr), string(id))

	return result, err
}

// implement Fake searcher for testing
type FakeOrderSearcher struct {
	fakeResponse []types.Order
	requests     []search.OrderSearchRequest

	fakeIdMap map[zeus.Uuid]types.Order
	fakeError error

	// On the nth occurrence of a call to this searcher, return the slice, otherwise default to `fakeResponse`
	onOccurrenceReturns map[int][]types.Order

	onOccurrenceCountReturns map[int]int
}

func NewFakeOrderSearcher(fakeResponse []types.Order) OrderSearcher {
	return &FakeOrderSearcher{
		fakeResponse:             fakeResponse,
		requests:                 []search.OrderSearchRequest{},
		fakeIdMap:                map[zeus.Uuid]types.Order{},
		fakeError:                nil,
		onOccurrenceReturns:      map[int][]types.Order{},
		onOccurrenceCountReturns: map[int]int{},
	}
}

func (r *FakeOrderSearcher) Search(searchRequest search.OrderSearchRequest) ([]types.Order, error) {
	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceReturns) > 0 {
		if occ, ok := r.onOccurrenceReturns[len(r.requests)]; ok {
			return occ, nil
		}
	}

	return r.fakeResponse, r.fakeError
}

func (r *FakeOrderSearcher) GetRequests() []search.OrderSearchRequest {
	return r.requests
}

func (r *FakeOrderSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.OrderSearchRequest) ([]types.Order, error) {
	return r.Search(searchRequest)
}

func (r *FakeOrderSearcher) Count(searchRequest search.OrderSearchRequest) (searcher.CountResult, error) {
	count := searcher.CountResult{
		Count: len(r.fakeResponse),
	}

	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceCountReturns) > 0 {
		if occ, ok := r.onOccurrenceCountReturns[len(r.requests)]; ok {
			count.Count = occ
			return count, nil
		}
	}

	return count, r.fakeError
}

func (r *FakeOrderSearcher) TxCount(tx *sqlx.Tx, searchRequest search.OrderSearchRequest) (searcher.CountResult, error) {
	return r.Count(searchRequest)
}

func (r *FakeOrderSearcher) ById(id zeus.Uuid) (types.Order, error) {
	if len(r.fakeIdMap) == 0 {
		return r.fakeResponse[0], nil
	}

	entity, ok := r.fakeIdMap[id]
	if !ok {
		return types.Order{}, errors.New("Not able to find Order by id: " + string(id))
	}

	return entity, r.fakeError
}

func (r *FakeOrderSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.Order, error) {
	return r.ById(id)
}

func (r *FakeOrderSearcher) SetByIdResponses(resp map[zeus.Uuid]types.Order) {
	r.fakeIdMap = resp
}

func (r *FakeOrderSearcher) SetError(err error) {
	r.fakeError = err
}

func (r *FakeOrderSearcher) GetFakeError() error {
	return r.fakeError
}

func (r *FakeOrderSearcher) GetOnOccurrenceReturns() map[int][]types.Order {
	return r.onOccurrenceReturns
}

func (r *FakeOrderSearcher) SetOnOccurrenceReturns(val map[int][]types.Order) {
	r.onOccurrenceReturns = val
}

func (r *FakeOrderSearcher) GetOnOccurrenceCountReturns() map[int]int {
	return r.onOccurrenceCountReturns
}

func (r *FakeOrderSearcher) SetOnOccurrenceCountReturns(val map[int]int) {
	r.onOccurrenceCountReturns = val
}
