// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package dbhandlers

import (
	"fmt"

	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/getbread/breadkit/zeus/updater"
	update "github.com/getbread/shopify_plugin_backend/service/update"
	"github.com/jmoiron/sqlx"
)

// interface for this updater
type OrderUpdater interface {
	Update(updateRequest update.OrderUpdateRequest) error
	TxUpdate(tx *sqlx.Tx, updateRequest update.OrderUpdateRequest) error
	DeleteById(id zeus.Uuid) error
	TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error
}

// implement SQL based updater
type sqlOrderUpdater struct {
	db *sqlx.DB
}

func newSqlOrderUpdater(db *sqlx.DB) OrderUpdater {
	return &sqlOrderUpdater{db: db}
}

func NewSqlOrderUpdater(db *sqlx.DB) OrderUpdater {
	return &sqlOrderUpdater{db: db}
}

func (r *sqlOrderUpdater) Update(updateRequest update.OrderUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for OrderUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlOrderUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.OrderUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for OrderUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlOrderUpdater) DeleteById(id zeus.Uuid) error {
	ur := update.OrderUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for OrderUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlOrderUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	ur := update.OrderUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for OrderUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

// implement Fake updater for testing
type FakeOrderUpdater struct {
	fakeResponse     error
	collectedUpdates []update.OrderUpdateRequest
	collectedDeletes []zeus.Uuid
}

func NewFakeOrderUpdater(fakeResponse error) OrderUpdater {
	return &FakeOrderUpdater{fakeResponse: fakeResponse}
}

func (r *FakeOrderUpdater) Update(updateRequest update.OrderUpdateRequest) error {
	r.collectedUpdates = append(r.collectedUpdates, updateRequest)
	return r.fakeResponse
}

func (r *FakeOrderUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.OrderUpdateRequest) error {
	return r.Update(updateRequest)
}

func (r *FakeOrderUpdater) DeleteById(id zeus.Uuid) error {
	r.collectedDeletes = append(r.collectedDeletes, id)
	return nil
}

func (r *FakeOrderUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	return r.DeleteById(id)
}

func (r *FakeOrderUpdater) GetCollectedUpdates() []update.OrderUpdateRequest {
	return r.collectedUpdates
}

func (r *FakeOrderUpdater) GetCollectedDeletes() []zeus.Uuid {
	return r.collectedDeletes
}
