// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package dbhandlers

import (
	"fmt"

	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/getbread/breadkit/zeus/updater"
	update "github.com/getbread/shopify_plugin_backend/service/update"
	"github.com/jmoiron/sqlx"
)

// interface for this updater
type PlusGatewayCheckoutUpdater interface {
	Update(updateRequest update.PlusGatewayCheckoutUpdateRequest) error
	TxUpdate(tx *sqlx.Tx, updateRequest update.PlusGatewayCheckoutUpdateRequest) error
	DeleteById(id zeus.Uuid) error
	TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error
}

// implement SQL based updater
type sqlPlusGatewayCheckoutUpdater struct {
	db *sqlx.DB
}

func newSqlPlusGatewayCheckoutUpdater(db *sqlx.DB) PlusGatewayCheckoutUpdater {
	return &sqlPlusGatewayCheckoutUpdater{db: db}
}

func NewSqlPlusGatewayCheckoutUpdater(db *sqlx.DB) PlusGatewayCheckoutUpdater {
	return &sqlPlusGatewayCheckoutUpdater{db: db}
}

func (r *sqlPlusGatewayCheckoutUpdater) Update(updateRequest update.PlusGatewayCheckoutUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for PlusGatewayCheckoutUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlPlusGatewayCheckoutUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.PlusGatewayCheckoutUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for PlusGatewayCheckoutUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlPlusGatewayCheckoutUpdater) DeleteById(id zeus.Uuid) error {
	ur := update.PlusGatewayCheckoutUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for PlusGatewayCheckoutUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlPlusGatewayCheckoutUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	ur := update.PlusGatewayCheckoutUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for PlusGatewayCheckoutUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

// implement Fake updater for testing
type FakePlusGatewayCheckoutUpdater struct {
	fakeResponse     error
	collectedUpdates []update.PlusGatewayCheckoutUpdateRequest
	collectedDeletes []zeus.Uuid
}

func NewFakePlusGatewayCheckoutUpdater(fakeResponse error) PlusGatewayCheckoutUpdater {
	return &FakePlusGatewayCheckoutUpdater{fakeResponse: fakeResponse}
}

func (r *FakePlusGatewayCheckoutUpdater) Update(updateRequest update.PlusGatewayCheckoutUpdateRequest) error {
	r.collectedUpdates = append(r.collectedUpdates, updateRequest)
	return r.fakeResponse
}

func (r *FakePlusGatewayCheckoutUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.PlusGatewayCheckoutUpdateRequest) error {
	return r.Update(updateRequest)
}

func (r *FakePlusGatewayCheckoutUpdater) DeleteById(id zeus.Uuid) error {
	r.collectedDeletes = append(r.collectedDeletes, id)
	return nil
}

func (r *FakePlusGatewayCheckoutUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	return r.DeleteById(id)
}

func (r *FakePlusGatewayCheckoutUpdater) GetCollectedUpdates() []update.PlusGatewayCheckoutUpdateRequest {
	return r.collectedUpdates
}

func (r *FakePlusGatewayCheckoutUpdater) GetCollectedDeletes() []zeus.Uuid {
	return r.collectedDeletes
}
