// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/searcher. DO NOT EDIT.

package dbhandlers

import (
	"errors"
	"fmt"
	"strings"

	"github.com/getbread/breadkit/zeus/searcher"
	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/jmoiron/sqlx"

	search "github.com/getbread/shopify_plugin_backend/service/search"
	types "github.com/getbread/shopify_plugin_backend/service/types"
)

// interface for this searcher
type PlusGatewayCheckoutSearcher interface {
	Search(searchRequest search.PlusGatewayCheckoutSearchRequest) ([]types.PlusGatewayCheckout, error)
	Count(searchRequest search.PlusGatewayCheckoutSearchRequest) (searcher.CountResult, error)
	ById(id zeus.Uuid) (types.PlusGatewayCheckout, error)

	TxSearch(tx *sqlx.Tx, searchRequest search.PlusGatewayCheckoutSearchRequest) ([]types.PlusGatewayCheckout, error)
	TxCount(tx *sqlx.Tx, searchRequest search.PlusGatewayCheckoutSearchRequest) (searcher.CountResult, error)
	TxById(tx *sqlx.Tx, id zeus.Uuid) (types.PlusGatewayCheckout, error)
}

// implement SQL based searcher
type sqlPlusGatewayCheckoutSearcher struct {
	db *sqlx.DB
}

func newSqlPlusGatewayCheckoutSearcher(db *sqlx.DB) PlusGatewayCheckoutSearcher {
	return &sqlPlusGatewayCheckoutSearcher{db}
}

func NewSqlPlusGatewayCheckoutSearcher(db *sqlx.DB) PlusGatewayCheckoutSearcher {
	return &sqlPlusGatewayCheckoutSearcher{db}
}

func (r *sqlPlusGatewayCheckoutSearcher) Search(searchRequest search.PlusGatewayCheckoutSearchRequest) ([]types.PlusGatewayCheckout, error) {
	results := []types.PlusGatewayCheckout{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for PlusGatewayCheckoutSearcher : %s", err.Error())
	}

	err = r.db.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlPlusGatewayCheckoutSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.PlusGatewayCheckoutSearchRequest) ([]types.PlusGatewayCheckout, error) {
	results := []types.PlusGatewayCheckout{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for PlusGatewayCheckoutSearcher : %s", err.Error())
	}

	err = tx.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlPlusGatewayCheckoutSearcher) Count(searchRequest search.PlusGatewayCheckoutSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for PlusGatewayCheckoutSearcher : %s", err.Error())
	}

	err = r.db.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlPlusGatewayCheckoutSearcher) TxCount(tx *sqlx.Tx, searchRequest search.PlusGatewayCheckoutSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for PlusGatewayCheckoutSearcher : %s", err.Error())
	}

	err = tx.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlPlusGatewayCheckoutSearcher) ById(id zeus.Uuid) (types.PlusGatewayCheckout, error) {
	result := types.PlusGatewayCheckout{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.PlusGatewayCheckoutSearchRequest{})

	err := r.db.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_plus_gateway_checkouts WHERE id=$1", fieldsStr), string(id))

	return result, err
}

func (r *sqlPlusGatewayCheckoutSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.PlusGatewayCheckout, error) {
	result := types.PlusGatewayCheckout{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.PlusGatewayCheckoutSearchRequest{})

	err := tx.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_plus_gateway_checkouts WHERE id=$1", fieldsStr), string(id))

	return result, err
}

// implement Fake searcher for testing
type FakePlusGatewayCheckoutSearcher struct {
	fakeResponse []types.PlusGatewayCheckout
	requests     []search.PlusGatewayCheckoutSearchRequest

	fakeIdMap map[zeus.Uuid]types.PlusGatewayCheckout
	fakeError error

	// On the nth occurrence of a call to this searcher, return the slice, otherwise default to `fakeResponse`
	onOccurrenceReturns map[int][]types.PlusGatewayCheckout

	onOccurrenceCountReturns map[int]int
}

func NewFakePlusGatewayCheckoutSearcher(fakeResponse []types.PlusGatewayCheckout) PlusGatewayCheckoutSearcher {
	return &FakePlusGatewayCheckoutSearcher{
		fakeResponse:             fakeResponse,
		requests:                 []search.PlusGatewayCheckoutSearchRequest{},
		fakeIdMap:                map[zeus.Uuid]types.PlusGatewayCheckout{},
		fakeError:                nil,
		onOccurrenceReturns:      map[int][]types.PlusGatewayCheckout{},
		onOccurrenceCountReturns: map[int]int{},
	}
}

func (r *FakePlusGatewayCheckoutSearcher) Search(searchRequest search.PlusGatewayCheckoutSearchRequest) ([]types.PlusGatewayCheckout, error) {
	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceReturns) > 0 {
		if occ, ok := r.onOccurrenceReturns[len(r.requests)]; ok {
			return occ, nil
		}
	}

	return r.fakeResponse, r.fakeError
}

func (r *FakePlusGatewayCheckoutSearcher) GetRequests() []search.PlusGatewayCheckoutSearchRequest {
	return r.requests
}

func (r *FakePlusGatewayCheckoutSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.PlusGatewayCheckoutSearchRequest) ([]types.PlusGatewayCheckout, error) {
	return r.Search(searchRequest)
}

func (r *FakePlusGatewayCheckoutSearcher) Count(searchRequest search.PlusGatewayCheckoutSearchRequest) (searcher.CountResult, error) {
	count := searcher.CountResult{
		Count: len(r.fakeResponse),
	}

	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceCountReturns) > 0 {
		if occ, ok := r.onOccurrenceCountReturns[len(r.requests)]; ok {
			count.Count = occ
			return count, nil
		}
	}

	return count, r.fakeError
}

func (r *FakePlusGatewayCheckoutSearcher) TxCount(tx *sqlx.Tx, searchRequest search.PlusGatewayCheckoutSearchRequest) (searcher.CountResult, error) {
	return r.Count(searchRequest)
}

func (r *FakePlusGatewayCheckoutSearcher) ById(id zeus.Uuid) (types.PlusGatewayCheckout, error) {
	if len(r.fakeIdMap) == 0 {
		return r.fakeResponse[0], nil
	}

	entity, ok := r.fakeIdMap[id]
	if !ok {
		return types.PlusGatewayCheckout{}, errors.New("Not able to find PlusGatewayCheckout by id: " + string(id))
	}

	return entity, r.fakeError
}

func (r *FakePlusGatewayCheckoutSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.PlusGatewayCheckout, error) {
	return r.ById(id)
}

func (r *FakePlusGatewayCheckoutSearcher) SetByIdResponses(resp map[zeus.Uuid]types.PlusGatewayCheckout) {
	r.fakeIdMap = resp
}

func (r *FakePlusGatewayCheckoutSearcher) SetError(err error) {
	r.fakeError = err
}

func (r *FakePlusGatewayCheckoutSearcher) GetFakeError() error {
	return r.fakeError
}

func (r *FakePlusGatewayCheckoutSearcher) GetOnOccurrenceReturns() map[int][]types.PlusGatewayCheckout {
	return r.onOccurrenceReturns
}

func (r *FakePlusGatewayCheckoutSearcher) SetOnOccurrenceReturns(val map[int][]types.PlusGatewayCheckout) {
	r.onOccurrenceReturns = val
}

func (r *FakePlusGatewayCheckoutSearcher) GetOnOccurrenceCountReturns() map[int]int {
	return r.onOccurrenceCountReturns
}

func (r *FakePlusGatewayCheckoutSearcher) SetOnOccurrenceCountReturns(val map[int]int) {
	r.onOccurrenceCountReturns = val
}
