// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/searcher. DO NOT EDIT.

package dbhandlers

import (
	"errors"
	"fmt"
	"strings"

	"github.com/getbread/breadkit/zeus/searcher"
	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/jmoiron/sqlx"

	search "github.com/getbread/shopify_plugin_backend/service/search"
	types "github.com/getbread/shopify_plugin_backend/service/types"
)

// interface for this searcher
type SessionSearcher interface {
	Search(searchRequest search.SessionSearchRequest) ([]types.Session, error)
	Count(searchRequest search.SessionSearchRequest) (searcher.CountResult, error)
	ById(id zeus.Uuid) (types.Session, error)

	TxSearch(tx *sqlx.Tx, searchRequest search.SessionSearchRequest) ([]types.Session, error)
	TxCount(tx *sqlx.Tx, searchRequest search.SessionSearchRequest) (searcher.CountResult, error)
	TxById(tx *sqlx.Tx, id zeus.Uuid) (types.Session, error)
}

// implement SQL based searcher
type sqlSessionSearcher struct {
	db *sqlx.DB
}

func newSqlSessionSearcher(db *sqlx.DB) SessionSearcher {
	return &sqlSessionSearcher{db}
}

func NewSqlSessionSearcher(db *sqlx.DB) SessionSearcher {
	return &sqlSessionSearcher{db}
}

func (r *sqlSessionSearcher) Search(searchRequest search.SessionSearchRequest) ([]types.Session, error) {
	results := []types.Session{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for SessionSearcher : %s", err.Error())
	}

	err = r.db.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlSessionSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.SessionSearchRequest) ([]types.Session, error) {
	results := []types.Session{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for SessionSearcher : %s", err.Error())
	}

	err = tx.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlSessionSearcher) Count(searchRequest search.SessionSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for SessionSearcher : %s", err.Error())
	}

	err = r.db.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlSessionSearcher) TxCount(tx *sqlx.Tx, searchRequest search.SessionSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for SessionSearcher : %s", err.Error())
	}

	err = tx.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlSessionSearcher) ById(id zeus.Uuid) (types.Session, error) {
	result := types.Session{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.SessionSearchRequest{})

	err := r.db.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_shops_sessions WHERE id=$1", fieldsStr), string(id))

	return result, err
}

func (r *sqlSessionSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.Session, error) {
	result := types.Session{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.SessionSearchRequest{})

	err := tx.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_shops_sessions WHERE id=$1", fieldsStr), string(id))

	return result, err
}

// implement Fake searcher for testing
type FakeSessionSearcher struct {
	fakeResponse []types.Session
	requests     []search.SessionSearchRequest

	fakeIdMap map[zeus.Uuid]types.Session
	fakeError error

	// On the nth occurrence of a call to this searcher, return the slice, otherwise default to `fakeResponse`
	onOccurrenceReturns map[int][]types.Session

	onOccurrenceCountReturns map[int]int
}

func NewFakeSessionSearcher(fakeResponse []types.Session) SessionSearcher {
	return &FakeSessionSearcher{
		fakeResponse:             fakeResponse,
		requests:                 []search.SessionSearchRequest{},
		fakeIdMap:                map[zeus.Uuid]types.Session{},
		fakeError:                nil,
		onOccurrenceReturns:      map[int][]types.Session{},
		onOccurrenceCountReturns: map[int]int{},
	}
}

func (r *FakeSessionSearcher) Search(searchRequest search.SessionSearchRequest) ([]types.Session, error) {
	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceReturns) > 0 {
		if occ, ok := r.onOccurrenceReturns[len(r.requests)]; ok {
			return occ, nil
		}
	}

	return r.fakeResponse, r.fakeError
}

func (r *FakeSessionSearcher) GetRequests() []search.SessionSearchRequest {
	return r.requests
}

func (r *FakeSessionSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.SessionSearchRequest) ([]types.Session, error) {
	return r.Search(searchRequest)
}

func (r *FakeSessionSearcher) Count(searchRequest search.SessionSearchRequest) (searcher.CountResult, error) {
	count := searcher.CountResult{
		Count: len(r.fakeResponse),
	}

	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceCountReturns) > 0 {
		if occ, ok := r.onOccurrenceCountReturns[len(r.requests)]; ok {
			count.Count = occ
			return count, nil
		}
	}

	return count, r.fakeError
}

func (r *FakeSessionSearcher) TxCount(tx *sqlx.Tx, searchRequest search.SessionSearchRequest) (searcher.CountResult, error) {
	return r.Count(searchRequest)
}

func (r *FakeSessionSearcher) ById(id zeus.Uuid) (types.Session, error) {
	if len(r.fakeIdMap) == 0 {
		return r.fakeResponse[0], nil
	}

	entity, ok := r.fakeIdMap[id]
	if !ok {
		return types.Session{}, errors.New("Not able to find Session by id: " + string(id))
	}

	return entity, r.fakeError
}

func (r *FakeSessionSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.Session, error) {
	return r.ById(id)
}

func (r *FakeSessionSearcher) SetByIdResponses(resp map[zeus.Uuid]types.Session) {
	r.fakeIdMap = resp
}

func (r *FakeSessionSearcher) SetError(err error) {
	r.fakeError = err
}

func (r *FakeSessionSearcher) GetFakeError() error {
	return r.fakeError
}

func (r *FakeSessionSearcher) GetOnOccurrenceReturns() map[int][]types.Session {
	return r.onOccurrenceReturns
}

func (r *FakeSessionSearcher) SetOnOccurrenceReturns(val map[int][]types.Session) {
	r.onOccurrenceReturns = val
}

func (r *FakeSessionSearcher) GetOnOccurrenceCountReturns() map[int]int {
	return r.onOccurrenceCountReturns
}

func (r *FakeSessionSearcher) SetOnOccurrenceCountReturns(val map[int]int) {
	r.onOccurrenceCountReturns = val
}
