// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/updater. DO NOT EDIT.

package dbhandlers

import (
	"fmt"

	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/getbread/breadkit/zeus/updater"
	update "github.com/getbread/shopify_plugin_backend/service/update"
	"github.com/jmoiron/sqlx"
)

// interface for this updater
type SessionUpdater interface {
	Update(updateRequest update.SessionUpdateRequest) error
	TxUpdate(tx *sqlx.Tx, updateRequest update.SessionUpdateRequest) error
	DeleteById(id zeus.Uuid) error
	TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error
}

// implement SQL based updater
type sqlSessionUpdater struct {
	db *sqlx.DB
}

func newSqlSessionUpdater(db *sqlx.DB) SessionUpdater {
	return &sqlSessionUpdater{db: db}
}

func NewSqlSessionUpdater(db *sqlx.DB) SessionUpdater {
	return &sqlSessionUpdater{db: db}
}

func (r *sqlSessionUpdater) Update(updateRequest update.SessionUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for SessionUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlSessionUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.SessionUpdateRequest) error {

	sqlStr, values, err := updater.GetUpdateSql(&updateRequest)

	if err != nil {
		return fmt.Errorf("Error generating update SQL for SessionUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlSessionUpdater) DeleteById(id zeus.Uuid) error {
	ur := update.SessionUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for SessionUpdater : %s", err.Error())
	}

	_, err = r.db.Exec(sqlStr, values.([]interface{})...)

	return err
}

func (r *sqlSessionUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	ur := update.SessionUpdateRequest{
		Id: id,
	}

	sqlStr, values, err := updater.GetDeleteSql(&ur)

	if err != nil {
		return fmt.Errorf("Error generating delete SQL for SessionUpdater : %s", err.Error())
	}

	_, err = tx.Exec(sqlStr, values.([]interface{})...)

	return err
}

// implement Fake updater for testing
type FakeSessionUpdater struct {
	fakeResponse     error
	collectedUpdates []update.SessionUpdateRequest
	collectedDeletes []zeus.Uuid
}

func NewFakeSessionUpdater(fakeResponse error) SessionUpdater {
	return &FakeSessionUpdater{fakeResponse: fakeResponse}
}

func (r *FakeSessionUpdater) Update(updateRequest update.SessionUpdateRequest) error {
	r.collectedUpdates = append(r.collectedUpdates, updateRequest)
	return r.fakeResponse
}

func (r *FakeSessionUpdater) TxUpdate(tx *sqlx.Tx, updateRequest update.SessionUpdateRequest) error {
	return r.Update(updateRequest)
}

func (r *FakeSessionUpdater) DeleteById(id zeus.Uuid) error {
	r.collectedDeletes = append(r.collectedDeletes, id)
	return nil
}

func (r *FakeSessionUpdater) TxDeleteById(tx *sqlx.Tx, id zeus.Uuid) error {
	return r.DeleteById(id)
}

func (r *FakeSessionUpdater) GetCollectedUpdates() []update.SessionUpdateRequest {
	return r.collectedUpdates
}

func (r *FakeSessionUpdater) GetCollectedDeletes() []zeus.Uuid {
	return r.collectedDeletes
}
