// Code generated by https://github.com/getbread/breadkit/zeus/tree/master/generators/searcher. DO NOT EDIT.

package dbhandlers

import (
	"errors"
	"fmt"
	"strings"

	"github.com/getbread/breadkit/zeus/searcher"
	zeus "github.com/getbread/breadkit/zeus/types"
	"github.com/jmoiron/sqlx"

	search "github.com/getbread/shopify_plugin_backend/service/search"
	types "github.com/getbread/shopify_plugin_backend/service/types"
)

// interface for this searcher
type ShopSearcher interface {
	Search(searchRequest search.ShopSearchRequest) ([]types.Shop, error)
	Count(searchRequest search.ShopSearchRequest) (searcher.CountResult, error)
	ById(id zeus.Uuid) (types.Shop, error)

	TxSearch(tx *sqlx.Tx, searchRequest search.ShopSearchRequest) ([]types.Shop, error)
	TxCount(tx *sqlx.Tx, searchRequest search.ShopSearchRequest) (searcher.CountResult, error)
	TxById(tx *sqlx.Tx, id zeus.Uuid) (types.Shop, error)
}

// implement SQL based searcher
type sqlShopSearcher struct {
	db *sqlx.DB
}

func newSqlShopSearcher(db *sqlx.DB) ShopSearcher {
	return &sqlShopSearcher{db}
}

func NewSqlShopSearcher(db *sqlx.DB) ShopSearcher {
	return &sqlShopSearcher{db}
}

func (r *sqlShopSearcher) Search(searchRequest search.ShopSearchRequest) ([]types.Shop, error) {
	results := []types.Shop{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for ShopSearcher : %s", err.Error())
	}

	err = r.db.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlShopSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.ShopSearchRequest) ([]types.Shop, error) {
	results := []types.Shop{}

	sqlStr, values, err := searcher.GetSelectSql(&searchRequest)

	if err != nil {
		return nil, fmt.Errorf("Error generating search SQL for ShopSearcher : %s", err.Error())
	}

	err = tx.Select(&results, sqlStr, values.([]interface{})...)

	if err != nil {
		if strings.Contains(err.Error(), "no rows in result set") {
			return results, nil
		}
	}

	return results, err
}

func (r *sqlShopSearcher) Count(searchRequest search.ShopSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for ShopSearcher : %s", err.Error())
	}

	err = r.db.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlShopSearcher) TxCount(tx *sqlx.Tx, searchRequest search.ShopSearchRequest) (searcher.CountResult, error) {
	result := searcher.CountResult{}

	sqlStr, values, err := searcher.GetCountSql(&searchRequest)

	if err != nil {
		return result, fmt.Errorf("Error generating count SQL for ShopSearcher : %s", err.Error())
	}

	err = tx.Get(&result, sqlStr, values.([]interface{})...)

	return result, err
}

func (r *sqlShopSearcher) ById(id zeus.Uuid) (types.Shop, error) {
	result := types.Shop{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.ShopSearchRequest{})

	err := r.db.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_shops WHERE id=$1", fieldsStr), string(id))

	return result, err
}

func (r *sqlShopSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.Shop, error) {
	result := types.Shop{}

	fieldsStr := searcher.GetSelectFieldsAvailable(&search.ShopSearchRequest{})

	err := tx.Get(&result, fmt.Sprintf("SELECT %s FROM shopify_shops WHERE id=$1", fieldsStr), string(id))

	return result, err
}

// implement Fake searcher for testing
type FakeShopSearcher struct {
	fakeResponse []types.Shop
	requests     []search.ShopSearchRequest

	fakeIdMap map[zeus.Uuid]types.Shop
	fakeError error

	// On the nth occurrence of a call to this searcher, return the slice, otherwise default to `fakeResponse`
	onOccurrenceReturns map[int][]types.Shop

	onOccurrenceCountReturns map[int]int
}

func NewFakeShopSearcher(fakeResponse []types.Shop) ShopSearcher {
	return &FakeShopSearcher{
		fakeResponse:             fakeResponse,
		requests:                 []search.ShopSearchRequest{},
		fakeIdMap:                map[zeus.Uuid]types.Shop{},
		fakeError:                nil,
		onOccurrenceReturns:      map[int][]types.Shop{},
		onOccurrenceCountReturns: map[int]int{},
	}
}

func (r *FakeShopSearcher) Search(searchRequest search.ShopSearchRequest) ([]types.Shop, error) {
	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceReturns) > 0 {
		if occ, ok := r.onOccurrenceReturns[len(r.requests)]; ok {
			return occ, nil
		}
	}

	return r.fakeResponse, r.fakeError
}

func (r *FakeShopSearcher) GetRequests() []search.ShopSearchRequest {
	return r.requests
}

func (r *FakeShopSearcher) TxSearch(tx *sqlx.Tx, searchRequest search.ShopSearchRequest) ([]types.Shop, error) {
	return r.Search(searchRequest)
}

func (r *FakeShopSearcher) Count(searchRequest search.ShopSearchRequest) (searcher.CountResult, error) {
	count := searcher.CountResult{
		Count: len(r.fakeResponse),
	}

	r.requests = append(r.requests, searchRequest)

	if len(r.onOccurrenceCountReturns) > 0 {
		if occ, ok := r.onOccurrenceCountReturns[len(r.requests)]; ok {
			count.Count = occ
			return count, nil
		}
	}

	return count, r.fakeError
}

func (r *FakeShopSearcher) TxCount(tx *sqlx.Tx, searchRequest search.ShopSearchRequest) (searcher.CountResult, error) {
	return r.Count(searchRequest)
}

func (r *FakeShopSearcher) ById(id zeus.Uuid) (types.Shop, error) {
	if len(r.fakeIdMap) == 0 {
		return r.fakeResponse[0], nil
	}

	entity, ok := r.fakeIdMap[id]
	if !ok {
		return types.Shop{}, errors.New("Not able to find Shop by id: " + string(id))
	}

	return entity, r.fakeError
}

func (r *FakeShopSearcher) TxById(tx *sqlx.Tx, id zeus.Uuid) (types.Shop, error) {
	return r.ById(id)
}

func (r *FakeShopSearcher) SetByIdResponses(resp map[zeus.Uuid]types.Shop) {
	r.fakeIdMap = resp
}

func (r *FakeShopSearcher) SetError(err error) {
	r.fakeError = err
}

func (r *FakeShopSearcher) GetFakeError() error {
	return r.fakeError
}

func (r *FakeShopSearcher) GetOnOccurrenceReturns() map[int][]types.Shop {
	return r.onOccurrenceReturns
}

func (r *FakeShopSearcher) SetOnOccurrenceReturns(val map[int][]types.Shop) {
	r.onOccurrenceReturns = val
}

func (r *FakeShopSearcher) GetOnOccurrenceCountReturns() map[int]int {
	return r.onOccurrenceCountReturns
}

func (r *FakeShopSearcher) SetOnOccurrenceCountReturns(val map[int]int) {
	r.onOccurrenceCountReturns = val
}
